### ISSUE TITLE
After reinstalling the system, how can I recover my heketi pre-config?

### ISSUE THREAD

**Issue by songfuxing** [heketi/heketi#1015]
I can't add device because the disk have been used, and how can I add the device and get data?

**Comment by obnoxxx** [comment]
@biggerStar thanks for reaching out!
Could you provide some more background?

**Comment by biggerStar** [comment]
The backgroud is : after a crash accident, we had to reinstall the CentOS system, the same, also need to reinstall heketi. After installation of the heketi, there was a problem: heketi could not add the old disk because the disk has been used , not a raw disk.
The way we solve the problem is：copy the old heketi's db file (```heketi.db```) to the new heketi,(/var/lib/heketi/heketi.db)
Could you tell me if this method can work? Or, Is there a better way to do it?

**Comment by phlogistonjohn** [comment]
@songfuxing if you had a copy of the heketi db where was it located? Was it on a heketidbstorage volume that survived the DR scenario? Normally, heketi is deployed so that the db is located on a gluster volume for HA purposes, but I'm not sure if that's the case for your deployment.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
