### ISSUE TITLE
Why there is no autodelete feature for gluster block hosting volume in all cases?

### ISSUE THREAD

**Issue by shekharberry** [heketi/heketi#1121]
## Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): heketi-cli 6.0.0

Hi,

Using CNS, I created gluster block volume and used for testing (All dynamically though, PVC was sent by app pods to SC and PV was serviced etc).  After deleting all the gluster block volume I wanted to create gluster file volume but was denied due to lack of available space. 
On further investigation I found gluster block hosting volume still persists even after last of gluster block volume is deleted.
I could proceed with creation of gluster file volume only after manually deleting this gluster block hosting volume.
 My question is why we do not auto-delete gluster block hosting volume after all block volumes are deleted?
Time to create new block hosting volume should not be an issue in case a new block volume request comes in as it takes only 10-20 sec to create a block hosting volume.

--Shekhar

**Comment by phlogistonjohn** [comment]
Hi,
A single block hosting volume is not one-to-one with the block volumes it contains. A block hosting volume may contain more than one block volume. The system can be configured (as it is by default IIRC) to create block hosting volumes if none exist but new block volume requests may re-use an existing block hosting volume. So, since the block hosting volume can be reused it doesn't quite fit the idea that the block hosting volume be deleted when the block volumes is deleted.

I understand this asymmetry could be inconvenient especially in a situation where there is not a lot of space available. Hopefully, I've explained the design choice to your satisfaction.

**Comment by phlogistonjohn** [comment]
Hopefully my answer was satisfactory. I'm closing this issue now. If you feel the issue needs additional discussion please feel free to reopen.
