### ISSUE TITLE
Use Case: Remove node from cluster

### ISSUE THREAD

**Issue by manachyn** [heketi/heketi#1164]
I'd like to be able to remove a node from cluster with migration of all bricks.
Use cases:
1. Distributed only volume:
- allocate new brick on another node or return error if it is not possible to do it
- add new brick to the volume
- remove old brick from the volume (gluster will rebalance data to new brick)

2. Replicated/Distributed replicated volume:
- allocate new brick on another node
- replace old brick by new one. This case currently is implemented with some limitations: e. g. it is not possible to replace one brick in volume with replica count = 2. We get error "Cannot replace brick ... as only 1 of 2 required peer bricks are online" (OnlineBrickCount (2 - 1) < QuorumBrickCount (2 / 2 + 1))
- remove old brick reducing replica count of volume, if it is not possible to allocate new brick

We can implement bricks migration through gluster cli, but there is no way to sync heketi db with gluster state (to remove old bricks, add new)

Are there any possible solutions for these cases in heketi?

**Comment by phlogistonjohn** [comment]
Unless I'm misunderstanding this issue heketi already supports removing a node via moving the bricks off that node (the devices of that node).

The supported sequence is:
heketi-cli node disable ID
heketi-cli node remove ID
Once the latter operation completes there will be no bricks on the node. Please be aware that the operation is subject to the usual constraints of placing bricks on new nodes. So you generally need 4 nodes so that the replica set places the bricks on 3 different nodes.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
