### ISSUE TITLE
Can it be used on centos6

### ISSUE THREAD

**Issue by chuck54430** [heketi/heketi#1176]
Can it be used on centos6? Which version is available for centos6?

**Comment by phlogistonjohn** [comment]
Heketi server and cli tool are written in golang, and thus generates static binaries by default. I recommend trying one of the release tarballs for your architecture. You can find the latest tarballs here:    https://github.com/heketi/heketi/releases/latest

You can also try running one of the heketi container images available at dockerhub (such as heketi/heketi:latest) if you have the infrastructure to run containers on centos6 (its been a while since I used that so I don't remember).

This project generally doesn't deal with packaging for specific distributions.

**Comment by phlogistonjohn** [comment]
I hope I've sufficiently answered your question. It has been a few months since last activity, so I'm closing this issue. Please feel free to reopen if you feel the question has not been answered.
