### ISSUE TITLE
docker builds failing 

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1186]
Heketi master builds at docker hub have been failing for around nine days. Until this is resolved heketi:dev images will be fairly stale compared to current master.

The failures are due to glide panicking. I was able to reproduce the panic on my local system after updating to the latest fedora base image. I don't have a solution/workaround yet.

This issue is a placeholder to indicate this issue is being investigated.

**Comment by phlogistonjohn** [comment]
The build passes if using gilde binaries from the upstream releases or if using a fedora 27 container image.

**Comment by nixpanic** [comment]
On Wed, May 16, 2018 at 01:07:13PM -0700, John Mulligan wrote:
> The build passes if using gilde binaries from the upstream releases or
> if using a fedora 27 container image.

I had problems with glide-0.12.1 from Fedora before, and have updated
the RPM to version 0.13.1. It seems there is already a bug against the
Fedora package requesting the update, but it has not been handled yet.
(https://bugzilla.redhat.com/1376219)

If we can confirm that the updated glide version fixes the segfault, we
should ask the assignee (with needinfo) to update the packae in Fedora
Rawhide and 28.

I'll run a (not so quick) test here. Downloading the whole dependency
chain including kubernetes seems to take a while...

**Comment by nixpanic** [comment]
Unfortunately updating glide to 0.13.1 does not fix the problem for me.
Builds on Fedora 28 also fail with that :-/

Running 'glide install -v' within a heketi repo causes a segfault and
the 'vendor' directory is incomplete. Experimenting a little bit more,
adding the following changes to the 0.13.1 version makes things work for
me:

- Masterminds/glide#953
- Masterminds/glide#956
- Masterminds/glide#990

My x86_64 packages are available from https://fedorapeople.org/~devos/tmp/glide-update.f28/
If useful, I could create a Fedora COPR so that it can be used with the
container build.

**Comment by phlogistonjohn** [comment]
Yeah, it seems like if glide is built against go 1.10 it can hit this. Go 1.10 appears to be (recently?) the version of Go in fedora 28. That's why it works with fedora 27 or with the release binaries from glide.

I have an experimental patch that just pulls in the glide binary from the glide release tarball. Is that worse than a COPR? Remember that we are only using this during the heketi build, the dockerfile uninstalls the rpm (among others).
