### ISSUE TITLE
Create PersistenceVolumeClaim with size less than 1GB

### ISSUE THREAD

**Issue by MiodragL** [heketi/heketi#1260]
We have multiple Kubernetes pods and each one has his own PersistenceVolumeClaim requests, but we only need 50 mb per pod, and heketi can' t create PVC with size less thanGB.
Can You tell me if there is any chance to create PersistenceVolumeClaim with size less than 1GB? 

Thanks

**Comment by phlogistonjohn** [comment]
Correct, the minimum size of a volume that Heketi will create is 1GB. I do not think the Heketi team has any plans to support volumes less than 1GB. I will leave the issue open for a while in case anyone else wishes to disagree.

**Comment by HackToHell** [comment]
@phlogistonjohn I am not sure why the minimum size requirements are fixed by hekti, looking through the code I can't see any obvious reason apart from the conversion why sizes less than 1 GB should not work. And we do have a user case for sharing a smaller volume. 

How is the minimum size of 1GB chosen?

**Comment by phlogistonjohn** [comment]
> @phlogistonjohn I am not sure why the minimum size requirements are fixed by hekti, looking through the code I can't see any obvious reason apart from the conversion why sizes less than 1 GB should not work. And we do have a user case for sharing a smaller volume.

In theory it could be made to work but it would involve a fair amount of internal changes. Please note that quite a few interfaces in the api, cli and db store values in multiples of GB. To resolve this fundamental types would need to be changed.

What is your use case? I'd like to hear it.

> How is the minimum size of 1GB chosen?

This predates my involvement in the project. I can't answer that question, unfortunately.

**Comment by HackToHell** [comment]
@phlogistonjohn We use gluster with the salt master in kubernetes and salt holds some keys and some config files, the total size of which doesn't exceed more than 200 mb tops. 

I went through the code and it does look like a lot of the changes will be conversions, can send a PR to support 0.5Gb (float in terms of GB to maintain API compatibility) if that's okay with you guys.

**Comment by phlogistonjohn** [comment]
Thanks for the update. I think I understand what you are trying to do.

I'm skeptical that using floats is the right approach. Floats have issues that make it an inappropriate type for storage amounts, IMO. If we really needed to support decimal points, a fixed point type would probably be more appropriate. However, I still think that would not be quite right. I think something more like a data storage version of time.Duration type for long term storage and go-units for parsing would probably be better. However, I have not thought this through as much as I think is warranted.

**Comment by obnoxxx** [comment]
I was actually planning to do this since a while, but we never got around to doing it... This issue is the same as #782. As I explained in https://github.com/heketi/heketi/issues/782#issuecomment-319214441, if I am not mistaken, GB is actually only used as the unit on the outer layers (API/cli). Internally, everything is converted to KiB. So we should just remove the artificial limitation by allowing other units than GiB on the API, GiB remaining the default unit.

**Comment by phlogistonjohn** [comment]
Unfortunately, it is not. All block volume sizes are done as multiples of GB.
I suppose you could argue that we might only change the behavior for the file volumes, and leave the block volume issue for another time. Regardless, I feel that this needs something of a brief design doc so we can discuss the impact of the changes to the API and storage (if needed).

**Comment by mykaul** [comment]
@phlogistonjohn - I'd start with files first of all - the main use case is clear - some have very few files, small, but they usually need to be shared among instances of apps.
Don't let perfect be the enemy of good.

**Comment by mykaul** [comment]
@obnoxxx - I'd be happy to see some progress on this.

**Comment by jgrumboe** [comment]
@phlogistonjohn I would like to add another use case.
We are searching for a possible problem related to the amount of volumes in a gluster. In a sandbox environment we would need to generate >350 volumes, but with this minsize of 1GB we would need 3x350GB minimun (because 3 nodes cluster) to just create them. And in this case I don't even want to store any data.
Additionally we also see many workloads with less than 512MB of persistent storage needed. So it's always a "waste" of storage.
I would also be very happy to see progress on this.

**Comment by mykaul** [comment]
I was under the impression we are thin-provisioning. I'm not sure we need all the space ahead of time (but certainly I agree there is a use case for small PVs!).

**Comment by jgrumboe** [comment]
@mykaul if you're referring to the thinpools which are created for each volume,  they are only used for snapshots of volumes.
Each volume needs its space inside the volumegroup and has a dedicated thinpool for storing snapshots.
So i would consider glusterfs as thick provisioned.

**Comment by nixpanic** [comment]
On Wed, Apr 03, 2019 at 06:51:37PM +0000, Johannes Grumböck wrote:
> @phlogistonjohn I would like to add another use case.
> We are searching for a possible problem related to the amount of volumes in a gluster. In a sandbox environment we would need to generate >350 volumes, but with this minsize of 1GB we would need 3x350GB minimun (because 3 nodes cluster) to just create them. And in this case I don't even want to store any data.
> Additionally we also see many workloads with less than 512MB of persistent storage needed. So it's always a "waste" of storage.

Depending on your needs, you may be interested in the "Gluster Subvol
provisioner" that we experimented a little with. At the moment there is
no intention to make the provisioner a 1st class component, and a (now)
better solution would be to have it as a CSI driver. However, the idea
works quite well if many Gluster volumes are needed.

The setup works similar to many NFS deployments, where one large
filesystem (here a Gluster Volume) is used, but the actual PV(C) is a
subdirectory on that filesystem. This does not involve Heketi, except
for the 1st Gluster Volume (named supervol) that will contain the
'subdirectory volumes'.

Some links:
- https://github.com/nixpanic/external-storage/blob/gluster/subvol/gluster/subvol/README.md
- https://github.com/nixpanic/external-storage/tree/gluster/subvol/gluster/subvol/examples

**Comment by raghavendra-talur** [comment]
@phlogistonjohn What do you think of the following changes

* add a dbattribute and upgrade procedure to change the db format to KiB
  ** this is independent and a prerequisite for the changes below
* adding a SizeWithUnit member to volume create request
** Change the validation of request from requiring size to require(size OR sizeWithUnit)
* add another flag to cli(sizeWithUnit) wherever we have size defaulting to int

If you think it is going in the right direction, I will make a design PR.

**Comment by jgrumboe** [comment]
@raghavendra-talur Your proposal would also include, that the current behaviour, to specify size without Unit, defaults to GiB, right? So the default behaviour would still work as normal (including for example Openshift Container Storage).

**Comment by phlogistonjohn** [comment]
@raghavendra-talur :

> @phlogistonjohn What do you think of the following changes
> 
>     * add a dbattribute and upgrade procedure to change the db format to KiB
>       ** this is independent and a prerequisite for the changes below
> 

Agreed on this point here, but we have to be a little careful because of the way some of the api types are used directly in the db.

>     * adding a SizeWithUnit member to volume create request
>       ** Change the validation of request from requiring size to require(size OR sizeWithUnit)
> 

I was thinking something slightly different, a new parameter (hypothetically) called "SizeUnit". If not provided SizeUnit is assumed to be "G".  If provided SizeUnit may be "G", or "M" or whatever units we choose to additionally support over time. This makes all POST methods inherently backwards compatible.
The only additional wrinkle wrt backwards compat is what we return on info requests. Anything old will look at the response and ignore the SizeUnit field (would apply to any new field). So this aspect will require some additional thought, but I think that also applies to "SizeWithUnit"

>     * add another flag to cli(sizeWithUnit) wherever we have size defaulting to int

For the cli, I'd just support specifying suffixes to the current size param. "--size 15M" vs "--size 10", etc.

> 
> 
> If you think it is going in the right direction, I will make a design PR.

Lets start a design pr. And we can go back and forth the the exact design there.

**Comment by TomaszKlosinski** [comment]
Any news on this?

**Comment by phlogistonjohn** [comment]
Unfortunately, it is doubtful the current maintenance team will work on this. I will put a help wanted label on this issue in case someone else wants to pick it up.

**Comment by phlogistonjohn** [comment]
Probably never going to happen. Closing
