### ISSUE TITLE
support other data backend

### ISSUE THREAD

**Issue by MartinForReal** [heketi/heketi#1333]
### Kind of issue
Feature request

### Observed behavior
BoltDB is the only storage data backend

### Expected/desired behavior
should support other remote data backend

**Comment by huzhengchuan** [comment]
etcd is a nice choice.

**Comment by phlogistonjohn** [comment]
While I appreciate the sentiment this is a fairly challenging task that would be rather invasive. If you're interested in testing things out that are not production ready yet, I suggest taking at look at [GlusterD2](https://github.com/gluster/glusterd2) which is the future replacement for glusterd as well as eventually taking over some of the management tasks currently performed by Heketi.

A number of the regular heketi devs are starting to contribute to that project for farther-future features while Heketi concentrates on stability and reliability for the current use cases. Because of this I'm going to close this issue as out-of-scope for the Heketi project. Feel free to reopen if you think the issue deserves additional discussion.
