### ISSUE TITLE
Thin pool for volumes

### ISSUE THREAD

**Issue by cloud-tools** [heketi/heketi#1355]
### Kind of issue
> Feature request

### Observed behavior
When Heketi creates a logical volume for a GlusterFS brick, it tries to use thin-provisioning and create a thin pool for each brick separately. 
But it doesn't work as designed - when Heketi creates a thin pool, the free space of a volume group is reduced by the claimed size of thin-pool, not by really provisioned size.

### Expected/desired behavior
Heketi should create a single thin-pool as soon as volume group has been created and use it as a source pool for thin-provisioned logical volumes.

### Details on how to reproduce (minimal and precise)
at gluster pod
$ lvs

### Information about the environment:

- Heketi version used v6.0.0 
- Operating system used: CentOs
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image:  v6
- Using kubernetes, openshift, or direct install:  openshift
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):  openshift-ansible

**Comment by phlogistonjohn** [comment]
> When Heketi creates a logical volume for a GlusterFS brick, it tries to use thin-provisioning and create a thin pool for each brick separately.

Yes, that's an accurate assessment.

> But it doesn't work as designed - when Heketi creates a thin pool, the free space of a volume group is reduced by the claimed size of thin-pool, not by really provisioned size.

I'm sorry but I don't understand what you mean by this. By default Heketi sizes the thin LV inside the thin pool to (roughly) the same size as the thin pool. You can also provide the snapshot factor parameter that will reduce the size of the thin LV relative to that of the thin pool and allow for gluster level snapshots to be made.

> Heketi should create a single thin-pool as soon as volume group has been created and use it as a source pool for thin-provisioned logical volumes.

We've considered doing this in the recent past. But I'd like to understand your use case a bit better. What motivated you to make this request?

**Comment by obnoxxx** [comment]
@phlogistonjohn writes:
> @cloud-tools writes:
> > When Heketi creates a logical volume for a GlusterFS brick, it tries to use thin-provisioning and create a thin pool for each brick separately.
> 
> Yes, that's an accurate assessment.

> > But it doesn't work as designed - when Heketi creates a thin pool, the free space of a volume group is reduced by the claimed size of thin-pool, not by really provisioned size.
> 
> I'm sorry but I don't understand what you mean by this. By default Heketi sizes the thin LV inside the thin pool to (roughly) the same size as the thin pool. You can also provide the snapshot factor parameter that will reduce the size of the thin LV relative to that of the thin pool and allow for gluster level snapshots to be made.

Indeed. The issue seems to mix a bug report "it is not working as designed" with a feature request "it should be done differently".

First of all, let me clarify that this is working exactly as designed: as you say, each brick that is carved out of a raw disk device gets its own thin pool. The thin pool for a brick can be somewhat larger than the actual requested brick size to account for snapshot space (see "snapshot factor" in the config). And that brick's thin-pool size (roughly brick-size * snapshot-factor) is abducted from the raw space of the volume group of the disk. So this is working just as designed.

@cloud-tools, if you disagree, please elaborate. Otherwise, we can concentrate on the RFE:

> > Heketi should create a single thin-pool as soon as volume group has been created and use it as a source pool for thin-provisioned logical volumes.
> 
> We've considered doing this in the recent past.

Right, this is a second mode that could be implemented in how heketi treats disk devices/vgs/tps/lvs ... It would gain us flexibility in using the space of a vg over the one-tp-per-brick approach. But the different bricks could also step on each other's toes wrt filling the space. One reason why we did not implement this yet is the possible I/O contention on the device if all LVs share one TP. We would need to do more research and experimentation about this.

> But I'd like to understand your use case a bit better. What motivated you to make this request?

**Comment by phlogistonjohn** [comment]
It is highly unlikely that heketi's general approach to how lvm volumes are created will change. Closing this issue.
