### ISSUE TITLE
How to clean up Heketi 8 / Gluster 4

### ISSUE THREAD

**Issue by vikramkhatri** [heketi/heketi#1366]
Platform: IBM ICP 3.1
Heketi: V8.0
Gluster: 4.0.2

## Situation:

I have a very big software helm chart and when it gets deployed through, it creates 20 PVCs and they all happen almost simultaneously. This leads VMs running gluster getting rebooted immediately. I understand that the capacity may not be large enough but this is a good test case to see the resiliency of any product.

I have a setup of 10 VMs running ICP 3.1 and gluster runs on 4 nodes and they each have 4 CPUs and 11 GB of RAM.

When VMs come back - Glusters are running but Heketi goes into `Init : 1/2` mode and the error says that there are pending operations and they need to be handled manually. Since we are talking about data, I get the sense that heavy-handed operations are avoided and left to a human being to take care of the operations which happened in a distress situation. (Good thing in the age of automation - let humans do something so that they have a job.)

I have gone through the [troubleshooting guide](https://github.com/heketi/heketi/blob/master/docs/troubleshooting.md) and tried to follow it as much as I could but still more information is needed on clean-up. I followed up `all sub-items under "pendingoperations" are removed as well as removing any volumes and bricks that have a non-empty "Pending"/"Id" value.`. 

And I modified the json and imported it back and did `/usr/bin/heketi-start.sh` and it is just throwing logs after logs such as:
```
[negroni] Completed 200 OK in 241.021µs
[negroni] Started GET /volumes/0a8e6559821088cd335cc5e1b6d3861e
[negroni] Completed 500 Internal Server Error in 414.821µs
[negroni] Started GET /clusters
[negroni] Completed 200 OK in 103.061µs
[negroni] Started GET /clusters/5d27850ca879b6f6ceb2be5d6ed01191
[negroni] Completed 200 OK in 144.921µs
[negroni] Started GET /volumes/0a8e6559821088cd335cc5e1b6d3861e
[negroni] Completed 500 Internal Server Error in 360.206µs
[negroni] Started GET /clusters
[negroni] Completed 200 OK in 59.129µs
[negroni] Started GET /clusters/5d27850ca879b6f6ceb2be5d6ed01191
[negroni] Completed 200 OK in 159.078µs
[negroni] Started GET /volumes/0a8e6559821088cd335cc5e1b6d3861e
```
I have saved the original json and database and this is my ignorance that I did not do a good cleanup.

The steps that I followed were: (when heketi is in 1/2 init mode)
```
storage-glusterfs-glusterfs-daemonset-4t8jx                      1/1       Running    2          15h
storage-glusterfs-glusterfs-daemonset-65fs7                      1/1       Running    3          15h
storage-glusterfs-glusterfs-daemonset-97k4p                      1/1       Running    4          15h
storage-glusterfs-glusterfs-daemonset-c2xkb                      1/1       Running    2          15h
storage-glusterfs-glusterfs-heketi-deployment-569d599d79-t5mt9   0/1       Init:1/2   0          2h
```
Notice the restart count for gluster and that is the source of the problem when more than 20 PVCs were asked to be created by the helm chart and the VMs couldn't handled and they got rebooted.

Note: The steps given below might require some tweaks based upon the platform you are running like OpenShift or Google or IBM. This is specific to IBM Cloud Private just based upon specific labels etc.

### Step-1: Get the heketi db.
```
HPOD=$(kubectl -n kube-system get pods --no-headers -l glusterfs=heketi-pod -o jsonpath='{.items[].metadata.name}')
kubectl -n kube-system -c init-heketi cp $HPOD:/var/lib/heketi/heketi.db .
```
### Step-2: Backup the database, export json and copy the json locally
```
kubectl -n kube-system -c init-heketi exec -it $HPOD -- mv -f /var/lib/heketi/heketi.db /heketi-old.db
kubectl -n kube-system -c init-heketi exec -it $HPOD -- heketi db export --dbfile /heketi-old.db --jsonfile /tmp/heketidb.json
kubectl -n kube-system -c init-heketi cp $HPOD:/tmp/heketidb.json .
```
### Step-3: Modify the json to remove the Pending Operations as per my understanding of the troubleshooting guide.

I edited the json in my favorite editor to do better search and replace.

### Step-5 : Copy json into the pod and import the json to create the database.

```
kubectl -n kube-system -c init-heketi cp heketidb.json $HPOD:/tmp
kubectl -n kube-system -c init-heketi exec -it $HPOD -- heketi db import --dbfile /var/lib/heketi/heketi.db --jsonfile /tmp/heketidb.json
```
### Step-6: Block restore from old database - comment 8th line in `/usr/bin/heketi-start.sh`
```
kubectl -n kube-system -c init-heketi exec -it $HPOD -- sed -i '8 s/^/#/' /usr/bin/heketi-start.sh
```

### Step-7: Start heketi
```
kubectl -n kube-system -c init-heketi exec -it $HPOD /usr/bin/heketi-start.sh
```

If I had removed entries properly than the `heketi` will start but it is not starting and getting these errors continuously.
```
[negroni] Started GET /volumes/0a8e6559821088cd335cc5e1b6d3861e
[negroni] Completed 500 Internal Server Error in 213.036µs
```

Of course - things were not done right. I will restore the database and redo again but my ignorance is the proper cleanup.

This is not a defect issue but a knowledge gap issue on my part. Can someone give a real world example how to do a proper clean up. This is easy to reproduce and I can attach `gluster volume list` and `heketi-cli volume list` and the difference between the two is the things that need a clean-up when VMs got overwhelmed and rebooted.

I hope that this was not too boring. Thank you for any one who provides an insight through a real example.

@ phlogistonjohn - Your name sounds familiar. There used to be a John Mulligan who used to work at Sun Microsystems way back. But may be you are different.

**Comment by phlogistonjohn** [comment]
> When VMs come back - Glusters are running but Heketi goes into Init : 1/2 mode and the error says that there are pending operations and they need to be handled manually. Since we are talking about data, I get the sense that heavy-handed operations are avoided and left to a human being to take care of the operations which happened in a distress situation. (Good thing in the age of automation - let humans do something so that they have a job.)

FWIW the troubleshooting guide does mention that you can set HEKETI_IGNORE_STALE_OPERATIONS=true in order to avoid having to clean up the pending operations prior to restarting heketi. A future release should have the ability to clean them up automatically on startup.

Your clean up steps all seem reasonable, but there's one thing I'm not sure about. Generally, you should only be exporting or copying the db after the heketi process has stopped. From your steps I can't tell if that's the case or not. If not, I highly recommend stopping heketi first.

Because that may make accessing the db file itself more difficult (there's no pod/container to exec into). There are two techniques I've used in the past when debugging this kind of scenario:
* Mount heketidbstorage gluster volume using the gluster mount. Usually we copy the heketi binary into the mount point before stopping the heketi pod. This allows us to be sure we're exporting the db with the same heketi binary that runs the server.
* Create a kubernetes job using the same container image and mount points as the heketi pod. In the job spec run the export command to a mounted volume or just run a "dummy command" like sleep and exec into that pod to run the export command and file copy manually.

> This is not a defect issue but a knowledge gap issue on my part. Can someone give a real world example how to do a proper clean up. This is easy to reproduce and I can attach gluster volume list and heketi-cli volume list and the difference between the two is the things that need a clean-up when VMs got overwhelmed and rebooted.

Yes, unfortunately this is not as simple as it ought to be. Generally, you can start by examining the "pendingoperations" key in the db export. Any item in that db will have a type code that you (unfortunately) need to match up with the source code (see apps/gluster/pendingop.go). The types will tell you what kind of operation was being performed and what items were being created or deleted (brick, volume, etc). Then you can create lists of items that need to be removed from the db along with the pending operation entries themselves.

That all said, I've done enough of these repairs to have automated parts of it with the following script:
https://github.com/phlogistonjohn/heketi/blob/jjm-python-tools/extras/tools/scrub.py
But **beware** this script is a use at your own risk sort of thing, because it is not in a PR and not tested along with the rest of the Heketi code. I've just found it useful in the past.

> phlogistonjohn - Your name sounds familiar. There used to be a John Mulligan who used to work at Sun Microsystems way back. But may be you are different.

Not me, I'm afraid. :-)

**Comment by phlogistonjohn** [comment]
Oh, I forgot to mention:
For the gluster nodes rebooting issue if you are able to consistently reproduce the reboot we should be able to try and see if its primarily creating the volumes or mounting them by attempting to create the same number of volumes directly from the heketi-cli. For example, create a script that creates many volumes in parallel. Please note that if you're using heketi version 8 then heketi ought to be throttling the client requests and only serving a maximum of eight requests at once, unless configured differently.

**Comment by phlogistonjohn** [comment]
We have released heketi v9 which has an auto-cleanup feature for stale pending operations.
And as mentioned there's always the scrub script just in case.
Thus I'm going to close this issue with the request that your retry with the new release. Please feel free to reopen this issue if the new version doesn't resolve the issue(s) for you.
