### ISSUE TITLE
Create Volume Build Failed: No space (but it is there)

### ISSUE THREAD

**Issue by grig-tar** [heketi/heketi#1537]
### Kind of issue

> Uncomment only one of these:
> 
Bug
> Feature request

### Observed behavior
There is 3 kubernetes nodes, on each of it running glusterd in container and 1 heketi container for whole cluster.
Trying to create volumes using Heketi, I get error messages saying there is no space left in my cluster, even when checking node info shows that there is enough space left in disk yet.
> [heketi] ERROR 2019/02/26 13:20:26 /src/github.com/heketi/heketi/apps/glusterfs/operations_manage.go:89: Create Volume Build Failed: No space

It is true and false (like as Schrödinger's cat). Heketi look at it own DB and there is no space. But physically, on devices there is a lot of space.

```
[root@glusterfs-heketi-0 /]# heketi-cli topology info

Cluster Id: 5da41a393c7b6708b9da369d883b5d53

    File: true
    Block: true

    Volumes:

    Nodes:

        Node Id: 25a6ce6efc80cb257862c5967d32edfe
        State: online
        Cluster Id: 5da41a393c7b6708b9da369d883b5d53
        Zone: 1
        Management Hostnames: 10.0.0.87
        Storage Hostnames: 10.0.0.87
        Devices:
                Id:93f03f6f2313115ca994c000234350b3   Name:/dev/xvdc2          State:online    Size (GiB):179     Used (GiB):178     Free (GiB):0
                        Bricks:

        Node Id: 89bc0dff3436a1159f62e75de1421557
        State: online
        Cluster Id: 5da41a393c7b6708b9da369d883b5d53
        Zone: 1
        Management Hostnames: 10.0.0.90
        Storage Hostnames: 10.0.0.90
        Devices:
                Id:3e5d88f4b18ccfecc05c83df989136fb   Name:/dev/xvdc2          State:online    Size (GiB):179     Used (GiB):178     Free (GiB):0
                        Bricks:

        Node Id: c65202cfb7ca24d86d4541aa89f37cd9
        State: online
        Cluster Id: 5da41a393c7b6708b9da369d883b5d53
        Zone: 1
        Management Hostnames: 10.0.0.91
        Storage Hostnames: 10.0.0.91
        Devices:
                Id:0a0b37d923fc9c7a2b29c85b9cafd732   Name:/dev/xvdc2          State:online    Size (GiB):179     Used (GiB):178     Free (GiB):0
                        Bricks:
```
Yes, free space is absent, but there is no bricks.
```
[root@glusterfs-heketi-0 /]# heketi-cli db dump | jq
{
  "clusterentries": {
    "5da41a393c7b6708b9da369d883b5d53": {
      "Info": {
        "id": "5da41a393c7b6708b9da369d883b5d53",
        "nodes": [
          "25a6ce6efc80cb257862c5967d32edfe",
          "89bc0dff3436a1159f62e75de1421557",
          "c65202cfb7ca24d86d4541aa89f37cd9"
        ],
        "volumes": [],
        "block": true,
        "file": false,
        "blockvolumes": []
      }
    }
  },
  "volumeentries": {},
  "brickentries": {},
  "nodeentries": {
    "25a6ce6efc80cb257862c5967d32edfe": {
      "State": "online",
      "Info": {
        "zone": 1,
        "hostnames": {
          "manage": [
            "10.0.0.87"
          ],
          "storage": [
            "10.0.0.87"
          ]
        },
        "cluster": "5da41a393c7b6708b9da369d883b5d53",
        "id": "25a6ce6efc80cb257862c5967d32edfe"
      },
      "Devices": [
        "93f03f6f2313115ca994c000234350b3"
      ]
    },
    "89bc0dff3436a1159f62e75de1421557": {
      "State": "online",
      "Info": {
        "zone": 1,
        "hostnames": {
          "manage": [
            "10.0.0.90"
          ],
          "storage": [
            "10.0.0.90"
          ]
        },
        "cluster": "5da41a393c7b6708b9da369d883b5d53",
        "id": "89bc0dff3436a1159f62e75de1421557"
      },
      "Devices": [
        "3e5d88f4b18ccfecc05c83df989136fb"
      ]
    },
    "c65202cfb7ca24d86d4541aa89f37cd9": {
      "State": "online",
      "Info": {
        "zone": 1,
        "hostnames": {
          "manage": [
            "10.0.0.91"
          ],
          "storage": [
            "10.0.0.91"
          ]
        },
        "cluster": "5da41a393c7b6708b9da369d883b5d53",
        "id": "c65202cfb7ca24d86d4541aa89f37cd9"
      },
      "Devices": [
        "0a0b37d923fc9c7a2b29c85b9cafd732"
      ]
    }
  },
  "deviceentries": {
    "0a0b37d923fc9c7a2b29c85b9cafd732": {
      "State": "online",
      "Info": {
        "name": "/dev/xvdc2",
        "storage": {
          "total": 188608512,
          "free": 983040,
          "used": 187625472
        },
        "id": "0a0b37d923fc9c7a2b29c85b9cafd732"
      },
      "Bricks": [],
      "NodeId": "c65202cfb7ca24d86d4541aa89f37cd9",
      "ExtentSize": 4096
    },
    "3e5d88f4b18ccfecc05c83df989136fb": {
      "State": "online",
      "Info": {
        "name": "/dev/xvdc2",
        "storage": {
          "total": 188608512,
          "free": 983040,
          "used": 187625472
        },
        "id": "3e5d88f4b18ccfecc05c83df989136fb"
      },
      "Bricks": [],
      "NodeId": "89bc0dff3436a1159f62e75de1421557",
      "ExtentSize": 4096
    },
    "93f03f6f2313115ca994c000234350b3": {
      "State": "online",
      "Info": {
        "name": "/dev/xvdc2",
        "storage": {
          "total": 188608512,
          "free": 983040,
          "used": 187625472
        },
        "id": "93f03f6f2313115ca994c000234350b3"
      },
      "Bricks": [],
      "NodeId": "25a6ce6efc80cb257862c5967d32edfe",
      "ExtentSize": 4096
    }
  },
  "blockvolumeentries": {},
  "dbattributeentries": {
    "DB_BRICK_HAS_SUBTYPE_FIELD": {
      "Key": "DB_BRICK_HAS_SUBTYPE_FIELD",
      "Value": "yes"
    },
    "DB_CLUSTER_HAS_FILE_BLOCK_FLAG": {
      "Key": "DB_CLUSTER_HAS_FILE_BLOCK_FLAG",
      "Value": "yes"
    },
    "DB_GENERATION_ID": {
      "Key": "DB_GENERATION_ID",
      "Value": "1e875c95b1cd526c34f581f8d21864b0"
    },
    "DB_HAS_PENDING_OPS_BUCKET": {
      "Key": "DB_HAS_PENDING_OPS_BUCKET",
      "Value": "yes"
    }
  },
  "pendingoperations": {}
}
```
And again almost all space used, but who ate it?
Device xvdc2 (the same on other hosts):
```
root@kube2:~# lsblk /dev/xvdc2
NAME  MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvdc2 202:34   0  180G  0 part
```
LV creation:
```
root@kube2:~# pvdisplay /dev/xvdc2
  --- Physical volume ---
  PV Name               /dev/xvdc2
  VG Name               vg_0a0b37d923fc9c7a2b29c85b9cafd732
  PV Size               180.00 GiB / not usable 131.00 MiB
  Allocatable           yes
  PE Size               4.00 MiB
  Total PE              46047
  Free PE               46047
  Allocated PE          0
  PV UUID               eg6U6N-tFIg-l309-C9Uv-HBSB-oMCn-rJ2LiR

root@kube2:~# lvcreate vg_0a0b37d923fc9c7a2b29c85b9cafd732 -L 1G
  Logical volume "lvol0" created.
root@kube2:~# lvremove vg_0a0b37d923fc9c7a2b29c85b9cafd732/lvol0
Do you really want to remove and DISCARD active logical volume lvol0? [y/n]: y
  Logical volume "lvol0" successfully removed
```

So, how I achieve this, as I think: After reboot all servers kernel modules dm-thin-pool and dm-snapshot was not loaded. But heketi tried to create volume, failed with this, but push info about creation in DB.
Some earlier in logs `https://pastebin.com/eYNUsHy6`
If it true, how can I clean DB and start using my space?

### Expected/desired behavior
If volume was not created - don't push info to DB. Probably)

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v8.0.0-1-g082b556-release-8
- Operating system used: Ubuntu 16.04
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: heketi/heketi:8
- Using kubernetes, openshift, or direct install: kubernetes 1.9.3
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: kubernetes container (glusterfs 3.10.1)
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): custom

**Comment by grig-tar** [comment]
I did `heketi-cli device resync <dev_id>` and it's looks good now. So I don't need help anymore, my space with me again. But bug is present - if there is no kernel modules loaded and modprobe is inaccessible (heketi running in container) then free space will ate with no volume created.

**Comment by phlogistonjohn** [comment]
Do you have any logging from the volume creation event that consumed the space? It could help us better determine where things first went wrong.

**Comment by grig-tar** [comment]
There is all what I have - https://megaupload.nz/b2E9x2vdbb/h_txt
Heketi started with old topology.
12:32 - Topology updated.
State of cluster flags `file=false` and `block=false`
13:04 - Flags updated.
I did nothing, just waiting for PVs.
13:08 - According to my assumption - there is no more space in the database.

I understand what 'Minimum brick size limit reached.  Out of space.' means - it is ok now.
But there also present separate error 'Create Volume Build Failed: No space' and as you can see in first post there is no space in db.

**Comment by phlogistonjohn** [comment]
That link seems to redirect me to an advertisement. Could you use a pastebin such as http://fpaste.org instead?

**Comment by grig-tar** [comment]
Of course I can. Sorry for megaupload, it's just too big for pastebin.
https://paste.fedoraproject.org/paste/4iLVHzaEwmzMfWCeZQgsKw

**Comment by phlogistonjohn** [comment]
Some things in the log that concern/confuse me:
1. New devices being added without error, and the log starts with:
```
stat: cannot stat '/var/lib/heketi/heketi.db': No such file or directory
Copied backup db to /var/lib/heketi/heketi.db
Heketi v8.0.0-1-g082b556-release-8
```
So the db is not "empty" at the start but changes to topology are being made. I'm not sure how you deployed but I personally do not recommend relying on heketi db being backed up to a secret as a persistence mechanism. It is not crash-safe.

2. In the topology info you provided the file flag is "true". In the db dump it is "false" in the logs it is false (at least at first):
```
[heketi] INFO 2019/02/26 12:32:11 Cluster 5da41a393c7b6708b9da369d883b5d53 lacks both block and file flags
[heketi] ERROR 2019/02/26 12:32:11 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry.go:577: No clusters eligible to satisfy create volume request
[heketi] ERROR 2019/02/26 12:32:11 /src/github.com/heketi/heketi/apps/glusterfs/operations_manage.go:89: Create Volume Build Failed: No space
```

This also implies that you gave topology info and db dump from different "times". Originally, I thought that your space might have been consumed by pending operations but the db dbump showed no pending operations, however now I'm not sure because I've confirmed some large differences beteween the db dump and the other info you provided.

3. At approximately " 2019/02/26 13:04:12" the cluster flages are modified. After that the volumes start getting to the execution phase of the operation but fail due to missing kernel modules. At least some of these operations go into a retry loop. Then around 2019/02/26 13:03:26 three more volumes are requested (in parallel). At least one of these fails out around "2019/02/26 13:05:16" with a No space error most likely due to the other ongoing volume create operations consuming (virtual) space on the device.
It then goes on like this for a while.

What I recommend next to to allow your system to quiesce so that you're no longer making any requests to heketi. You can optionally use a command like `heketi-cli server mode set local-client` to force heketi to decline any new requests from any source other than localhost. Once the system is in this state check if there are pending operations via `heketi-cli server operations info` if there are any in-flight, stale, or failed operations these count against the free space on the devices in the heketi db.

Before continuing you will then want to make sure kernel modules are set up correctly on your nodes. You can run lvcreate commands simlar to those found in the heketi logs to validate the modules are available (make sure to clean the test lvs up afterwards).

Finally you need to ensure there are no more pending operations in the heketi db. This can be done using the operations cleanup funtionality that's new to heketi, OR, export the db uding `heketi db export ...` and then manually fix the db to remove any pending volumes and bricks. I can provide additional help here if you want it. 

Once everything is cleaned up, import the edited db (heketi db import ...) and restart heketi. Then do a simple test-volume creation using `heketi-cli volume create` command.

**Comment by grig-tar** [comment]
Thank you for big answer. We have much of automation and some times some parts works not so good together. We are on the way to fix it.
1. Yes, all data, except of backup of db in secret (forgot), was dropped after previous installation.
2. Yes, topology info and db dump are shifted in time.

Next time I will try to follow your advice, but now I have lost this environment and can’t check anything. So the ticket can be closed, I think.

**Comment by phlogistonjohn** [comment]
Understood. If you can reproduce any of the issues you previously saw feel free to reopen this issue or file another one. I hope your new deployments go smoother.
