### ISSUE TITLE
Heketi-Gluster snapshot create failed

### ISSUE THREAD

**Issue by bakonyip** [heketi/heketi#1587]
Hi,
I will create snaphot on glusterfs volume. I write heketi-cli volume snapshot command, but does not know this command and show "heketi-cli volume" command help screen.
Please help me, how to used snapshot creation in heketi volume.

Heketi version:
```
[root@heketi-85dbbbb55-k2c97 /]# heketi-cli --version
heketi-cli v9.0.0
```

I read this documentation:
https://github.com/heketi/heketi/blob/master/docs/design/snapshot.md

**Comment by phlogistonjohn** [comment]
That is a design document and thus a proposal, not documentation of implemented features.
To the best of my knowledge heketi currently only supports creating clone volumes and not snapshots directly. If you can use the clone volumes instead of direct snapshots please try that.
Otherwise, you will need to wait for or help with developing the proposed features.

**Comment by phlogistonjohn** [comment]
No updates in a few months. Closing. Please reopen if this is still relevant to you.
