### ISSUE TITLE
Heketi pod is a single point of failure

### ISSUE THREAD

**Issue by mrmarcsmith** [heketi/heketi#1605]
### Kind of issue

Feature request

### Observed behavior
When using Heketi and gluster for data storage in a K8s cluster, it is absolutely critical for us that there not be a single point of failure. I haven’t found a way to spin up a “backup” heketi node in case my primary pod goes down? 

For example, let’s say I lose the physical node that hosts the heketi pod. 
A. How long would it take for Kubernetes to automatically “re-create” the pod? Keeping in mind that all persistent data (databases etc) on our cluster be unavailable during that time.
B. Would kubernetes even be able to “re-create” the pod automatically or would it require manual intervention?

### Expected/desired behavior
Either educate me on how to spin up a backup heketi pod or open a PR to add this feature to heketi

**Comment by phlogistonjohn** [comment]
> ### Kind of issue
> 
> Feature request
> ### Observed behavior
> 
> When using Heketi and gluster for data storage in a K8s cluster, it is absolutely critical for us that there not be a single point of failure. I haven’t found a way to spin up a “backup” heketi node in case my primary pod goes down?
> 
> For example, let’s say I lose the physical node that hosts the heketi pod.
> A. How long would it take for Kubernetes to automatically “re-create” the pod? Keeping in mind that all persistent data (databases etc) on our cluster be unavailable during that time.

Let me clarify the latter half of this point. Heketi only works at the "management" layer and interfaces with the rest of the gluster stack. If heketi is down you can not create and delete volumes automatically through PVCs as well as management functions like device remove will be unavailable. However, heketi is not involved in the availability of the data in those volumes. Once the PV has been created the PV should contain enough data that clients (k8s volume mount) connects directly to gluster for data. Assuming a typical setup of 3 or 4 gluster nodes, as long as enough gluster nodes are up applications can still mount and access data into those volumes regardless of the status of heketi itself.

The time k8s takes to re-create a heketi pod when the pod has failed varies a bit. It often depends on the configuration of the liveness probe as well as if the heketi container image is available on the other nodes or if it needs to be pulled from the internet. I don't want to suggest any hard numbers here because they're bound to be wrong for someone. I suggest creating a test cluster and trying it out to get some estimates for your environment.


> B. Would kubernetes even be able to “re-create” the pod automatically or would it require manual intervention?

Typically, yes. I usually recommend [gluster-kubernetes](https://github.com/gluster/gluster-kubernetes) to help deploy the heketi+gluster suite because it confgures heketi as a deployment, and this will restart heketi on another node automatically. In addition it configures heketi's own db to be stored on a glusterfs volume such that the db is replicated and available from multiple nodes.

You can also investigate openshift-ansible which can also deploy heketi+gluster if you are using openshift. It works similarly.

However, if you planned on building it all from scratch you'd have to take care to configure it all correctly. Thus I strongly recommend gluster-kubernetes, etc.

> ### Expected/desired behavior
> 
> Either educate me on how to spin up a backup heketi pod or open a PR to add this feature to heketi

I hope I've answered all your questions and that using tools from the wider gluster containers ecosystem you should be able to already accomplish what you requested. Feel free to follow up with any additional questions, or close this issue if you are satisfied.

**Comment by mrmarcsmith** [comment]
Amazing. Thank you so much for the detailed clarification. That’s makes a LOT more sense as to why no one seems to be concerned about a backup for heketi and also how heketi can recreate itself after a failure. Much appreciated!
