### ISSUE TITLE
heketi-cli setup-openshift-heketi-storage error

### ISSUE THREAD

**Issue by andriktr** [heketi/heketi#1608]
Hi,
For some reason when I executing heketi-cli setup-openshift-heketi-storage ~ after 10 mins I’m getting an error “Error: Get http://10.47.0.4:8080/queue/878903ad0787b5f0fd31a8e056652756: dial tcp 10.47.0.4:8080: socket: too many open files”. 
Maybe somebody have seen something similar to this? 
Also If I’m trying to execute same command again I immediately getting an error Error: Failed to allocate new volume: Volume name ‘heketidbstorage’ already in use. 
Also heketi-storage.json is not created.
Thanks in advance

**Comment by phlogistonjohn** [comment]
Internally, heketi is asynchronous but the client mimics synchronous behavior by polling the server for results. It sounds like you encountered a case where the client made the request to the server but during the polling the server exhausted the fd limit. This is probably related to an existing issue around how the server (doesn't) reuse connections. I can't find the issue at the moment but if I do I'll link it here.
Does your environment restrict fd use such that the limit is lower than typical setups?

**Comment by andriktr** [comment]
Hi John, 
Thank you for your reply. 
This is actually my test environment and I'm pretty sure that nothing were changed for FD limits. 
My current setup is 2 masters and 3 worker nodes. Each worker node have one OS and one raw disk. I'm planning to use this additional RAW disk on worker nodes to build GlusterFS cluster and use it for dynamic PVCs provisioning. Maybe you can suggest any logs which I should look into and they might be helpful to better understand and investigate the issue. 

I also noticed that after error  if I execute "heketi-cli db dump" it  shows pending operations for some time, but after a while it's automatically cleans up and then I can execute  heketi-cli setup-kubernetes-heketi-storage command again. 

Also as far as I understand when you saying "server" in my particular setup this is container image running in  "deploy-heketi-77b68ffb9c-w8s2r" pod. Maybe it be useful to try to take a look on some logs in this particular pod?

All heketi-cli commands are being executed from one of the master nodes. 
Thanks for help in advance.

**Comment by phlogistonjohn** [comment]
Are you manually deploying things or are you using something like [gluster-kubernetes](https://github.com/gluster/gluster-kubernetes)?

**Comment by andriktr** [comment]
Hi, Yes I deploying things manualy, My steps are pretty much the same as described here:
[https://medium.com/faun/configuring-ha-kubernetes-cluster-on-bare-metal-servers-with-glusterfs-metallb-2-3-c9e0b705aa3d](https://medium.com/faun/configuring-ha-kubernetes-cluster-on-bare-metal-servers-with-glusterfs-metallb-2-3-c9e0b705aa3d)
The only difference is that I'm using real disks for Gluster instead of  fake block devices.

**Comment by phlogistonjohn** [comment]
Hmmm. OK, I haven't read through that whole article but its rather unfortunate that something that seems to be written this year is setting up heketi manually and not with gluster-kubernetes. That script really automates a lot of the tedious parts, has up-to-date templates, and avoids changes for manual error. If you can adapt this procedure to use gluster-kubernetes I'd highly recommend it.
However, if you can't use g-k at this time I can suggest that you try running the heketi-cli commands from within the pod (especially for this setup) rather than directly on hosts. IOW, if a step is "heketi-cli ... foo ..bar" do "kubectl exec -it <heketi-pod> -- heketi-cli ... foo ..bar".
This accomplishes two things, first you know that you are using a heketi-cli from the exact same build as the server and avoids any potential networking roadbumps between the client and server, at least until after heketi is fully set up.

**Comment by andriktr** [comment]
I Will try to play with heketi-cli directly in a pod just for interest how it will work this way.
And for sure I should agree with you that gluster-kubernetes should be a preferred deployment way. 
I Will let you know about results. 
Thanks

**Comment by andriktr** [comment]
The issue was that the heketi-cli version was 8.0 heketi-server version was 9.0. So I when  I updated heketi-cli version to the same version as a server  everything went as expected. 
Thank you.
