### ISSUE TITLE
Heketi-cli not installed with yum

### ISSUE THREAD

**Issue by mojighahar** [heketi/heketi#1615]
### Kind of issue

Bug

### Observed behavior
heketi-cli doesn't installed by this command etheir epel enabled or not:
yum install heketi

### Expected/desired behavior
heketi-cli being installed

### Details on how to reproduce (minimal and precise)
Run this command in CentOS 7 1810 build:
yum install heketi

### Information about the environment:

- Heketi version used: v8.0.0
- Operating system used: CentOS 7 build 1810
- Heketi compiled from sources, as a package (rpm/deb), or container: yum
- Using kubernetes, openshift, or direct install: direct

**Comment by phlogistonjohn** [comment]
This project is not responsible for how the distributions package this software. 
However I just happen to know that the name of the package you want is 'heketi-client' the 'heketi' package only contains the server.
I hope this helps but because this it out of our control I will preemptively close this issue.
