### ISSUE TITLE
cannot remove device with bricks

### ISSUE THREAD

**Issue by 0asp0** [heketi/heketi#1628]
### Kind of issue
Bug

### Observed behavior
I run glusterfs with heketi in kubernetes.  I need to free up a device which already has some bricks in it.

what I wanted to do:
- disable device
- remove device
- delete device

on remove I get following error:
```
Error: Failed to remove device, error: Cannot replace brick 536681db039f498cda08173b85f2103d as only 1 of 2 required peer bricks are online
command terminated with exit code 255
```

### Expected/desired behavior
After setting device offline the bricks should be replicated to another enabled device. I have enough devices with free space on other nodes, so there should be no problem moving the bricks.

### Details on how to reproduce (minimal and precise)
- having 3 nodes with to devices each
- create glusterfs pvc with 2 replicas
- disable device where are bricks on
- remove the disabled device

### Information about the environment:

- Heketi version used (heketi-cli v9.0.0): 
- Operating system used:  centos 7, kubernetes 1.14
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):  gk-deploy

### Other useful information
I added some nodes manually via heketi after initial setup with topology file.

**Comment by phlogistonjohn** [comment]
Could you please provide more logging for context? Specifically I want to double check this message is originating with a gluster command and I want to check which one. Thanks!

**Comment by amgads** [comment]
I just created a new issue #1630 and just found it's similar. output of the heketi-cli command:

2019-07-28 15:42:01 : INFO : Command (/usr/bin/heketi-cli node info c18a68d74772310a42264b52bbec4d1b) was succussful: (Node Id: c18a68d74772310a42264b52bbec4d1b
State: online
Cluster Id: 5a10f8c37f4efa1ddf34f8dd1b0fd3e3
Zone: 1
Management Hostname: gfs-02
Storage Hostname: 172.16.1.20
Devices:
Id:ed0659cd69eb3d1a3c7b0f4c584ff6cf   Name:/dev/vdd            State:online    Size (GiB):19      Used (GiB):2       Free (GiB):17      Bricks:1       
)
2019-07-28 15:42:02 : INFO : Command (/usr/bin/heketi-cli device disable ed0659cd69eb3d1a3c7b0f4c584ff6cf) was succussful: (Device ed0659cd69eb3d1a3c7b0f4c584ff6cf is now offline
2019-07-28 15:42:04 : ERROR : Command (/usr/bin/heketi-cli device remove ed0659cd69eb3d1a3c7b0f4c584ff6cf) failed: (Error: Failed to remove device, error: Cannot replace brick 0a7a5821de0e7a8ebbd6cb9568c0c00b as only 1 of 2 required peer bricks are online
)

What other logs you want?

**Comment by phlogistonjohn** [comment]
More heketi logs, specifically the commands run on the nodes. These log lines include where the commands are being run (what node/pod) and what command was run along with the output.
If its long you can put it on something like fpaste.org.

**Comment by raghavendra-talur** [comment]
The error message is coming from https://github.com/heketi/heketi/blob/b8472582311c71d8c6e444123e55814e1aa2ea9a/apps/glusterfs/volume_entry_allocate.go#L189 and the calculation quorum bricks is from https://github.com/heketi/heketi/blob/fc15a500b23bce241bdde2e6a52706aeffbb51e4/apps/glusterfs/volume_durability_replica.go#L78 .

This logic works for all replica counts which are 
1. odd
2. greater than 2

As the the volume in question is a replica 2, device replace does not work for it.

Immediately, I cannot think of a workaround in heketi to bypass this check.

Let us know why you are trying to free up the device. May be just disabling it is enough and new volumes will be created on new devices eventually bringing usage to similar levels on all devices?

**Comment by amgads** [comment]
[root@gfsl-01 tasks]# kubectl exec -n ncms heketi-594b859cfd-7mdnj -- heketi_cli.py device disable ba067ed0ac020c7e4f74ea6af8d67ad0
Device ba067ed0ac020c7e4f74ea6af8d67ad0 is now offline

[root@gfs-01 tasks]# kubectl exec -n ncms heketi-594b859cfd-7mdnj -- heketi_cli.py device remove ba067ed0ac020c7e4f74ea6af8d67ad0
Error: Failed to remove device, error: Cannot replace brick ed612b9f957fad064d409c4dc8aad01a as only 1 of 2 required peer bricks are online

command terminated with exit code 2
[root@gfs-01 tasks]# 

Attached the log segment for the two commands - few seconds prior to running the commands
The device I was trying to remove is on node gfs-01 (modified from full name for security)
logs is collected using:
kubectl logs <heketi-pod>
======================================
[cmdexec] INFO 2019/07/29 15:57:17 Check Glusterd service status in node gfs-03
[cmdexec] DEBUG 2019/07/29 15:57:17 heketi/pkg/remoteexec/ssh/ssh.go:172:ssh.(*SshExec).ExecCommands: Ran command [/bin/bash -c 'sudo systemctl status glusterd'] on gfs-03:22: Stdout [â— glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/etc/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-07-28 17:09:45 UTC; 22h ago
 Main PID: 28374 (glusterd)
    Tasks: 41
   Memory: 44.5M (limit: 512.0M)
   CGroup: /system.slice/glusterd.service
           â”œâ”€ 1107 /usr/sbin/glusterfsd -s 172.16.1.16 --volfile-id vol_1634e155acaa3b80998dfab4266d16c8.172.16.1.16.var-lib-heketi-mounts-vg_8fc8f5ed1d2417c347fff95c04c20d1e-brick_030c3086039db52783a7a52741c7c73d-brick -p /var/run/gluster/vols/vol_1634e155acaa3b80998dfab4266d16c8/172.16.1.16-var-lib-heketi-mounts-vg_8fc8f5ed1d2417c347fff95c04c20d1e-brick_030c3086039db52783a7a52741c7c73d-brick.pid -S /var/run/gluster/267b757f12ea66ad.socket --brick-name /var/lib/heketi/mounts/vg_8fc8f5ed1d2417c347fff95c04c20d1e/brick_030c3086039db52783a7a52741c7c73d/brick -l /var/log/glusterfs/bricks/var-lib-heketi-mounts-vg_8fc8f5ed1d2417c347fff95c04c20d1e-brick_030c3086039db52783a7a52741c7c73d-brick.log --xlator-option *-posix.glusterd-uuid=db73cb81-67f0-40e2-a4ff-d857731ce381 --process-name brick --brick-port 49152 --xlator-option vol_1634e155acaa3b80998dfab4266d16c8-server.listen-port=49152 --xlator-option transport.socket.bind-address=172.16.1.16
           â”œâ”€ 1343 /usr/sbin/glusterfs -s 172.16.1.16 --volfile-id gluster/glustershd -p /var/run/gluster/glustershd/glustershd.pid -l /var/log/glusterfs/glustershd.log -S /var/run/gluster/ff5a5072ea170c10.socket --xlator-option *replicate*.node-uuid=db73cb81-67f0-40e2-a4ff-d857731ce381 --process-name glustershd --client-pid=-6
           â””â”€28374 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level ERROR

Jul 28 17:09:45 gfs-03 systemd[1]: Starting GlusterFS, a clustered file-system server...
Jul 28 17:09:45 gfs-03 systemd[1]: Started GlusterFS, a clustered file-system server.
]: Stderr []
[asynchttp] INFO 2019/07/29 15:57:50 asynchttp.go:288: Started job cd8462c66426de6d025340e6be4fa49d
[asynchttp] INFO 2019/07/29 15:57:50 asynchttp.go:292: Completed job cd8462c66426de6d025340e6be4fa49d in 38.394664ms
[negroni] 2019-07-29T15:57:50Z | 202 | 	 109.351784ms | 10.254.0.101:8080 | POST /devices/ba067ed0ac020c7e4f74ea6af8d67ad0/state
[negroni] 2019-07-29T15:57:50Z | 204 | 	 79.786726ms | 10.254.0.101:8080 | GET /queue/cd8462c66426de6d025340e6be4fa49d
[asynchttp] INFO 2019/07/29 15:57:59 asynchttp.go:288: Started job 1668fd43f7846d39d3c0f1a1716d21a9
[negroni] 2019-07-29T15:57:59Z | 202 | 	 187.482114ms | 10.254.0.101:8080 | POST /devices/ba067ed0ac020c7e4f74ea6af8d67ad0/state
[negroni] 2019-07-29T15:57:59Z | 200 | 	 154.938Âµs | 10.254.0.101:8080 | GET /queue/1668fd43f7846d39d3c0f1a1716d21a9
[cmdexec] INFO 2019/07/29 15:57:59 Check Glusterd service status in node gfs-01
[cmdexec] DEBUG 2019/07/29 15:57:59 heketi/pkg/remoteexec/ssh/ssh.go:172:ssh.(*SshExec).ExecCommands: Ran command [/bin/bash -c 'sudo systemctl status glusterd'] on gfs-01:22: Stdout [â— glusterd.service - GlusterFS, a clustered file-system server
   Loaded: loaded (/etc/systemd/system/glusterd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-07-22 04:01:51 UTC; 1 weeks 0 days ago
 Main PID: 31652 (glusterd)
    Tasks: 41
   Memory: 76.6M (limit: 512.0M)
   CGroup: /system.slice/glusterd.service
           â”œâ”€21688 /usr/sbin/glusterfsd -s 172.16.1.19 --volfile-id vol_b11c7a2e90a6f69fedf31d03604de65b.172.16.1.19.var-lib-heketi-mounts-vg_ba067ed0ac020c7e4f74ea6af8d67ad0-brick_ed612b9f957fad064d409c4dc8aad01a-brick -p /var/run/gluster/vols/vol_b11c7a2e90a6f69fedf31d03604de65b/172.16.1.19-var-lib-heketi-mounts-vg_ba067ed0ac020c7e4f74ea6af8d67ad0-brick_ed612b9f957fad064d409c4dc8aad01a-brick.pid -S /var/run/gluster/95316887e30ab741.socket --brick-name /var/lib/heketi/mounts/vg_ba067ed0ac020c7e4f74ea6af8d67ad0/brick_ed612b9f957fad064d409c4dc8aad01a/brick -l /var/log/glusterfs/bricks/var-lib-heketi-mounts-vg_ba067ed0ac020c7e4f74ea6af8d67ad0-brick_ed612b9f957fad064d409c4dc8aad01a-brick.log --xlator-option *-posix.glusterd-uuid=fd89a77c-3543-41ac-b06f-9a8b9abd9f58 --process-name brick --brick-port 49152 --xlator-option vol_b11c7a2e90a6f69fedf31d03604de65b-server.listen-port=49152 --xlator-option transport.socket.bind-address=172.16.1.19
           â”œâ”€21715 /usr/sbin/glusterfs -s 172.16.1.19 --volfile-id gluster/glustershd -p /var/run/gluster/glustershd/glustershd.pid -l /var/log/glusterfs/glustershd.log -S /var/run/gluster/1485c1bfd0945248.socket --xlator-option *replicate*.node-uuid=fd89a77c-3543-41ac-b06f-9a8b9abd9f58 --process-name glustershd --client-pid=-6
           â””â”€31652 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level ERROR

Jul 22 04:01:51 gfs-01 systemd[1]: Starting GlusterFS, a clustered file-system server...
Jul 22 04:01:51 gfs-01 systemd[1]: Started GlusterFS, a clustered file-system server.
]: Stderr []
[cmdexec] DEBUG 2019/07/29 15:58:00 heketi/pkg/remoteexec/ssh/ssh.go:172:ssh.(*SshExec).ExecCommands: Ran command [/bin/bash -c 'sudo gluster --mode=script --timeout=600 volume info vol_b11c7a2e90a6f69fedf31d03604de65b --xml'] on gfs-01:22: Stdout [<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cliOutput>
  <opRet>0</opRet>
  <opErrno>0</opErrno>
  <opErrstr/>
  <volInfo>
    <volumes>
      <volume>
        <name>vol_b11c7a2e90a6f69fedf31d03604de65b</name>
        <id>55dbe85e-b942-427b-b922-54d9164dc715</id>
        <status>1</status>
        <statusStr>Started</statusStr>
        <snapshotCount>0</snapshotCount>
        <brickCount>2</brickCount>
        <distCount>2</distCount>
        <stripeCount>1</stripeCount>
        <replicaCount>2</replicaCount>
        <arbiterCount>0</arbiterCount>
        <disperseCount>0</disperseCount>
        <redundancyCount>0</redundancyCount>
        <type>2</type>
        <typeStr>Replicate</typeStr>
        <transport>0</transport>
        <bricks>
          <brick uuid="fd89a77c-3543-41ac-b06f-9a8b9abd9f58">172.16.1.19:/var/lib/heketi/mounts/vg_ba067ed0ac020c7e4f74ea6af8d67ad0/brick_ed612b9f957fad064d409c4dc8aad01a/brick<name>172.16.1.19:/var/lib/heketi/mounts/vg_ba067ed0ac020c7e4f74ea6af8d67ad0/brick_ed612b9f957fad064d409c4dc8aad01a/brick</name><hostUuid>fd89a77c-3543-41ac-b06f-9a8b9abd9f58</hostUuid><isArbiter>0</isArbiter></brick>
          <brick uuid="d52f242b-f50d-494a-a9ad-53de9d1d7c0d">172.16.1.14:/var/lib/heketi/mounts/vg_04fb0ebf27e75c926e421f6ac974936c/brick_8cab6a89338bc2f7b862cfd48c7aa386/brick<name>172.16.1.14:/var/lib/heketi/mounts/vg_04fb0ebf27e75c926e421f6ac974936c/brick_8cab6a89338bc2f7b862cfd48c7aa386/brick</name><hostUuid>d52f242b-f50d-494a-a9ad-53de9d1d7c0d</hostUuid><isArbiter>0</isArbiter></brick>
        </bricks>
        <optCount>4</optCount>
        <options>
          <option>
            <name>user.heketi.id</name>
            <value>b11c7a2e90a6f69fedf31d03604de65b</value>
          </option>
          <option>
            <name>transport.address-family</name>
            <value>inet</value>
          </option>
          <option>
            <name>nfs.disable</name>
            <value>on</value>
          </option>
          <option>
            <name>performance.client-io-threads</name>
            <value>off</value>
          </option>
        </options>
      </volume>
      <count>1</count>
    </volumes>
  </volInfo>
</cliOutput>
]: Stderr []
[cmdexec] DEBUG 2019/07/29 15:58:00 heketi/executors/cmdexec/volume.go:287:cmdexec.(*CmdExecutor).VolumeInfo: {OpRet:0 OpErrno:0 OpErrStr: VolInfo:{XMLName:{Space: Local:volInfo} Volumes:{XMLName:{Space: Local:volumes} Count:1 VolumeList:[{XMLName:{Space: Local:volume} VolumeName:vol_b11c7a2e90a6f69fedf31d03604de65b ID:55dbe85e-b942-427b-b922-54d9164dc715 Status:1 StatusStr:Started BrickCount:2 DistCount:2 StripeCount:1 ReplicaCount:2 ArbiterCount:0 DisperseCount:0 RedundancyCount:0 Type:2 TypeStr:Replicate Transport:0 Bricks:{XMLName:{Space: Local:bricks} BrickList:[{UUID:fd89a77c-3543-41ac-b06f-9a8b9abd9f58 Name:172.16.1.19:/var/lib/heketi/mounts/vg_ba067ed0ac020c7e4f74ea6af8d67ad0/brick_ed612b9f957fad064d409c4dc8aad01a/brick HostUUID:fd89a77c-3543-41ac-b06f-9a8b9abd9f58 IsArbiter:0} {UUID:d52f242b-f50d-494a-a9ad-53de9d1d7c0d Name:172.16.1.14:/var/lib/heketi/mounts/vg_04fb0ebf27e75c926e421f6ac974936c/brick_8cab6a89338bc2f7b862cfd48c7aa386/brick HostUUID:d52f242b-f50d-494a-a9ad-53de9d1d7c0d IsArbiter:0}]} OptCount:4 Options:{XMLName:{Space: Local:options} OptionList:[{Name:user.heketi.id Value:b11c7a2e90a6f69fedf31d03604de65b} {Name:transport.address-family Value:inet} {Name:nfs.disable Value:on} {Name:performance.client-io-threads Value:off}]}}]}}}
[negroni] 2019-07-29T15:58:00Z | 200 | 	 158.992Âµs | 10.254.0.101:8080 | GET /queue/1668fd43f7846d39d3c0f1a1716d21a9
[cmdexec] DEBUG 2019/07/29 15:58:00 heketi/pkg/remoteexec/ssh/ssh.go:172:ssh.(*SshExec).ExecCommands: Ran command [/bin/bash -c 'sudo gluster --mode=script --timeout=600 volume heal vol_b11c7a2e90a6f69fedf31d03604de65b info --xml'] on gfs-01:22: Stdout [<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cliOutput>
  <healInfo>
    <bricks>
      <brick hostUuid="fd89a77c-3543-41ac-b06f-9a8b9abd9f58">
        <name>172.16.1.19:/var/lib/heketi/mounts/vg_ba067ed0ac020c7e4f74ea6af8d67ad0/brick_ed612b9f957fad064d409c4dc8aad01a/brick</name>
        <status>Connected</status>
        <numberOfEntries>0</numberOfEntries>
      </brick>
      <brick hostUuid="d52f242b-f50d-494a-a9ad-53de9d1d7c0d">
        <name>172.16.1.14:/var/lib/heketi/mounts/vg_04fb0ebf27e75c926e421f6ac974936c/brick_8cab6a89338bc2f7b862cfd48c7aa386/brick</name>
        <status>Connected</status>
        <numberOfEntries>0</numberOfEntries>
      </brick>
    </bricks>
  </healInfo>
  <opRet>0</opRet>
  <opErrno>0</opErrno>
  <opErrstr/>
</cliOutput>
]: Stderr []
[cmdexec] DEBUG 2019/07/29 15:58:00 heketi/executors/cmdexec/volume.go:435:cmdexec.(*CmdExecutor).HealInfo: {OpRet:0 OpErrno:0 OpErrStr: HealInfo:{XMLName:{Space: Local:healInfo} Bricks:{BrickList:[{HostUUID:fd89a77c-3543-41ac-b06f-9a8b9abd9f58 Name:172.16.1.19:/var/lib/heketi/mounts/vg_ba067ed0ac020c7e4f74ea6af8d67ad0/brick_ed612b9f957fad064d409c4dc8aad01a/brick Status:Connected NumberOfEntries:0} {HostUUID:d52f242b-f50d-494a-a9ad-53de9d1d7c0d Name:172.16.1.14:/var/lib/heketi/mounts/vg_04fb0ebf27e75c926e421f6ac974936c/brick_8cab6a89338bc2f7b862cfd48c7aa386/brick Status:Connected NumberOfEntries:0}]}}}
[heketi] ERROR 2019/07/29 15:58:00 heketi/apps/glusterfs/device_entry.go:493:glusterfs.(*DeviceEntry).removeBricksFromDevice: Failed to remove device, error: Cannot replace brick ed612b9f957fad064d409c4dc8aad01a as only 1 of 2 required peer bricks are online
[heketi] ERROR 2019/07/29 15:58:00 heketi/apps/glusterfs/operations_manage.go:158:glusterfs.runOperationAfterBuild: Remove Device Failed: Failed to remove device, error: Cannot replace brick ed612b9f957fad064d409c4dc8aad01a as only 1 of 2 required peer bricks are online
[heketi] ERROR 2019/07/29 15:58:00 heketi/apps/glusterfs/operations_manage.go:172:glusterfs.runOperationAfterBuild: Max tries (1) consumed
[heketi] ERROR 2019/07/29 15:58:00 heketi/apps/glusterfs/operations_manage.go:242:glusterfs.RunOperation.func1: Error in Remove Device: Failed to remove device, error: Cannot replace brick ed612b9f957fad064d409c4dc8aad01a as only 1 of 2 required peer bricks are online
[asynchttp] INFO 2019/07/29 15:58:00 asynchttp.go:292: Completed job 1668fd43f7846d39d3c0f1a1716d21a9 in 1.664595887s
[negroni] 2019-07-29T15:58:01Z | 500 | 	 196.563Âµs | 10.254.0.101:8080 | GET /queue/1668fd43f7846d39d3c0f1a1716d21a9

**Comment by amgads** [comment]
Updated the ticket

**Comment by amgads** [comment]
any update/feedback?

**Comment by amgads** [comment]
Hi talur:
This scenario happens during recovery. We delete the device on that node. Are you saying disable will move the brick to another node? 
I thought that happens when you remove device. 
This is an existing class (replica=2) we have to maintain. We started now using replica=3 with arbiter which works fine when removing the device. 

I'll try the disable device and see if it works, however there're recovery scenarios where you need have a new now/devices and so you'll  need to remove the device

**Comment by amgads** [comment]
Hi Talur:
As I stated, brick doesn't move with just disable whether the replica is 2 or 3
with replica 3, it's moved right after 'device remove'. With replica-2, an error is returned and brick is not moved.
The error is that cannot replace the brick
Error: Failed to remove device, error: Cannot replace brick 1646fd3ce8db6d3bb374505593838d50 as only 1 of 2 required peer bricks are online

Any other suggestion?

**Comment by amgads** [comment]
BTW this function was working in heketi v5

**Comment by amgads** [comment]
Is there a way in heketi to grow volumes that are currently using a class with replicate:2 to have 3-bricks instead of 2? This will allow removing a device during recovery without failure

**Comment by phlogistonjohn** [comment]
Not natively, no. I suggest creating a new replica-3 volume, copying the contents from the old volume to the new, and then deleting the replica 2 volume. If that's not possible you might be able to add a brick to the volume via gluster and then hand-edit the heketi db to match but that's quite risky imo.

**Comment by amgads** [comment]
But this volume is created an attached to an application pod? How do you handle that if created 3 replica? I mean how to copy it. During a recovery of the node the other replica is being accessed by the application?

**Comment by amgads** [comment]
Is there a way to run both heketi v9 and v5 on the same pod? So we’d use v5 for the recovery of the replica 2 volume?

**Comment by amgads** [comment]
Can you also elaborate on how to edit the dB and what’s the risk?

**Comment by phlogistonjohn** [comment]
> But this volume is created an attached to an application pod? How do you handle that if created 3 replica? I mean how to copy it. During a recovery of the node the other replica is being accessed by the application?

Create the new volume. Temporarily stop the application pod. Either create a new application pod that accesses both volumes OR mount both volumes manually from a gluster pod/node. Use copy tools such as cp/rsync/etc to migrate data from one gluster volume to the other. Unmount volumes or stop copy pod. Edit pod spec of original pod to use new volume. Restart application pod and verify that it is working properly. 

> Is there a way to run both heketi v9 and v5 on the same pod? So we’d use v5 for the recovery of the replica 2 volume?

No that is not possible.



> Can you also elaborate on how to edit the dB and what’s the risk?

Heketi has tools for dumping the binary db to JSON and restoring JSON to the db format. So, you can export the db to json, edit it and restore it, making heketi think the addtional brick existed all along. The risks are that the format is not formally documented and you should have a strong understanding of how the heketi db works before trying to edit it.  If the edit is not correct you run the risk of having heketi fail to start or start but have a volume that isn't completely like a normal replica 3 volume, and thus still not be able to manage it.

**Comment by amgads** [comment]
Thx John.
One question regarding the last point (DB), When you say add brick to the json file, do you mean just adding a device or a brick to the volume?
If the later, heketi creates bricks with certain names and Id such:
Node Id: cf5f87d7cbd4fcedf5f4ec7b486ac587
        State: online
        Cluster Id: 7670958f7106363e7ae902cc6d070b09
        Zone: 1
        Management Hostname: 172.16.1.9
        Storage Hostname: 172.16.1.9
        Devices:
                Id:8b233385a269282edd537f6b9bf21789   Name:/dev/vdc            State:online    Size (GiB):24      Used (GiB):2       Free (GiB):22      
                        Bricks:
                                Id:a4ddfebdad5714d56732379d6827de5a   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_8b233385a269282edd537f6b9bf21789/brick_a4ddfebdad5714d56732379d6827de5a/brick

How do you accomplish that in the db?

**Comment by phlogistonjohn** [comment]
Heh. This is why I hesitated to mention the db edit method and mentioned its riskiness... its very involved and while its probably tempting to you you'd probably have to learn a lot about the internals of heketi.
I really think you're better off copying the data to a new volume.

**Comment by amgads** [comment]
Thx John. Certainly I'd like to know the later one. to try as well. The issue with copying the volume is application has to be down. Also, we need to continue to manage volumes in the future using heketi.

Are you saying you create the 3-replica (I assume could be 3 with arbiter) using heketi and then copy? Do you copy only one brick and depend on replication to sync?
If that's the case, is there a way to upgrade the storage class from replicate:2 to replicate:3?

**Comment by amgads** [comment]
Would updating the DB be with the brick added using gluster CLI -- same id, etc?

**Comment by amgads** [comment]
I expanded the volume from 2 replicas to 3 bricks (with anrbiter) using the gluster CLI. dumped the db to .json file. However, I realized that the db needs the brick ID which i can't determine. Any idea? also how do you load back the db .json file back?

**Comment by olivergregorius** [comment]
Having the same problem. Any progress on this issue?

**Comment by amgads** [comment]
tested after building from master and still fail
.......
Error: Failed to remove device, error: Cannot replace brick e5258aad22c3963a4ec4418b4d77dfe3 as only 1 of 2 required peer bricks are online

**Comment by GounGG** [comment]
> tested after building from master and still fail
> .......
> Error: Failed to remove device, error: Cannot replace brick e5258aad22c3963a4ec4418b4d77dfe3 as only 1 of 2 required peer bricks are online

me too，is there a solution？
