### ISSUE TITLE
is heketi supported on Redhat version 8?

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1658]
### Other useful information

Is heketi supported on RedHat 8?

**Comment by phlogistonjohn** [comment]
I'm assuming you mean RHEL 8 and not Red Hat Linux 8, which was [released in 2002](https://en.wikipedia.org/wiki/Red_Hat_Linux#Version_history). :-)
We don't specifically test on any version of RHEL and we don't currently test on the new CentOS 8 but I don't see a reason why it won't work. Please feel free to try it out and report any specific errors if you encounter any.
Please also note that if you choose to use containerized heketi the host os version matters very little because heketi itself doesn't interact directly with the OS it is running on.

**Comment by phlogistonjohn** [comment]
I'm going to assume this answer was satisfactory and close the issue. If you have issues building or running on RHEL8 feel free to reopen this issue or open a new issue for the specific problem.
