### ISSUE TITLE
New v10 release?

### ISSUE THREAD

**Issue by holmesb** [heketi/heketi#1675]
There are some [cool features and bug fixes](https://github.com/heketi/heketi/compare/v9.0.0...master) since v9 was released in April.  Not least Tag Matching.  Any chance of a v10 release to avoid having to deploy the master build?

Thanks

**Comment by amgads** [comment]
Second!

**Comment by amgads** [comment]
Are there nightly builds? if yes, where are they?

**Comment by amgads** [comment]
Why heketi doesn't have a planned release dates as glusterfs? Who controls that? Not knowing the target date for the next release is not a good planning practice especially for those having deployments in the field in tier one customers!!!!!!!!!

**Comment by howels** [comment]
We also need a clear Heketi roadmap and alignment with GlusterFS releases would be ideal. Especially as it seems like GD2 is no longer maintained and we will all need to use Heketi for the foreseeable future.

**Comment by superbiche** [comment]
> If you are a Heketi user who likes it and plans to continue using it please consider contributing to the project.

I guess @phlogistonjohn and other contributors won't continue building the project until maintainers want to take the lead.

I just started learning Go so I won't be able to write code, but I'd be more than happy to make some room in our CI infrastructure to manage nightly build and releases, and Docker images. 
Just need to know the maintainers are OK with that

**Comment by amarts** [comment]
I thought of leaving an update here in this issue on something new available for the gluster users in container eco-systems to consume. Have a look at [the kadalu project](https://github.com/kadalu/kadalu) some of us started. This is an alternative management layer for glusterfs (or say no management layer). As of today, it is in v0.4 version, and many features are still being done. 

We are still in the process of getting many features, but more feedback would only help the project grow better. Thanks for reading.

**Comment by phlogistonjohn** [comment]
Trying to quickly touch on some of the points brought up in this issue:

* Yes, we would like to do a release. We wanted to at least finish up some of the other nearly-done PRs and finish some work related to finally making device replace a proper operation rather than a hack. However our time has been limited, esp. mine due to personal issues.

* We do not do time based releases in heketi and I don't think we plan to.

* More help would be very welcome. We primarily need people to review PRs and triage issues. Our CI mostly works and the project release flow is not the blocking aspect IMO. Non-public ci would not be much help to the project but more public ci capability would be welcome, so please feel free to discuss enhancements to that flow in a new PR or issue.

* I'm not super thrilled to see what looks like an advertisement for an unrelated project in this thread but I won't complain too much.

**Comment by phlogistonjohn** [comment]
Oh, and I forgot to mention that container builds of master are continuously built on dockerhub. See: https://hub.docker.com/r/heketi/heketi
If you run standalone you're probably better off just building from source but if someone wants to contribute nightly builds of just the binaries I'd be happy to review PRs for that (although IMO container images are just as good or better than the raw binaries).

**Comment by amgads** [comment]
John:

Appreciate your answers! Since I can build heketi now and learning go -- I hope I can contribute soon.
Now, a couple of quick question:
a) Is there a rough estimate for Release 10 based on the current status?
    Mainly, so we can have own roadmap to use in June or September (allowing at least 6 weeks for integration)
b) If can't tell, what would be a stable "tag" we can build ourself if needed!

your answers are very appreciated as usual

**Comment by howels** [comment]
Any updates on V10? We're not sure about the overall progress of features outside of individual PRs, would really appreciate the maintainers tagging a new point release even if they don't feel like stamping a major version on this.

**Comment by phlogistonjohn** [comment]
v10.0.0 is out: https://github.com/heketi/heketi/releases/tag/v10.0.0

For any issues about the release or otherwise, please file new issues, thanks!

**Comment by amgads** [comment]
Thanks John -- for the good news
