### ISSUE TITLE
k8s svc and heketi volumes are not deleted after the termination of an application with large number of volumes

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1686]
### Kind of issue
> Bug
This is blocking to large scale applications!

### Observed behavior
It is observed that after the termination of our application which includes lots of gluster volumes, all the pvc, pv etc are all deleted. However, the k8s services relate to the glusterfs services show not deleted and even the gluster volume list also shows that there are many gluster volumes which are not getting deleted even after waiting for more than 1 hour after the application termination.
The number of services that are not deleted and the number of gluster volumes that are not deleted after application termination seems to match.
hekete v9.0.0 provides asyc operations for volume creation, but doesn't have the same for the delete. That's why can't delete large number of volumes one shot as this is done using helm charts.
If deleting the volumes manually in small chunks, they get deleted.

### Expected/desired behavior
delete volumes should allow async opertions similar to the create volume and should be configurable similar to the create volume:

"max_inflight_operations": 64,
"operation_retry_limits": {
"volume_create": 8

### Details on how to reproduce (minimal and precise)
Intsall an application (containers) with 40+ gluster volumes - then delete the application one time. You can use charts or any other form.

You'll find gluster service related instances not deleted and also gluster volumes
kubectl get svc ...
gluster volume list

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  v9.0.0
- Operating system used:  Linux
- Heketi compiled from sources, as a package (rpm/deb), or container: own container built using tar package
- If container, which container image: own
- Using kubernetes, openshift, or direct install: k8s
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: k8s gluster storage-class
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):  other

**Comment by phlogistonjohn** [comment]
Volume delete is implemented very similar to volume create and is async (in the same manner as create). If you use the heketi api you can see this by making N requests at once an seeing the in-flight counter go up to match (up to max_inflight_operations which you are aware of).

It sounds to me this might be more of an issue with the k8s provisioner.  You note that if you delete a few volumes at a time they do get removed. Can you reproduce without spawning lots of application and just by creating and deleting pvc requests?

**Comment by amgads** [comment]
Can you reproduce without spawning lots of application and just by creating and deleting pvc requests?
Can clarify what do you mean by that?

We have one application creating 30+ pvcs .. is that what you mean? if not please clarify

**Comment by amgads** [comment]
We used the following in heketi.json file for the create:
"max_inflight_operations": 64,
"operation_retry_limits": {
"volume_create": 8

Is there something similar for the delete?

**Comment by phlogistonjohn** [comment]
> Can you reproduce without spawning lots of application and just by creating and deleting pvc requests?
> Can clarify what do you mean by that?
> 
> We have one application creating 30+ pvcs .. is that what you mean? if not please clarify

What I mean is that if we forget about the way you are hitting this scenario in the real world, can we reproduce the behavior you're seeing artificially (like with a shell script running kubectl).



> We used the following in heketi.json file for the create:
> "max_inflight_operations": 64,
> "operation_retry_limits": {
> "volume_create": 8
> 
> Is there something similar for the delete? I mean for the operation_retry_limits!!

For somewhat historical reasons volume create is special in that it has an internal retry mechanism. It's the only operation that retries internally that way. However that doesn't really impact the async nature of the operation and if I had a time machine I would undo that decision and make everything that needs to retry, retry at the client side. That said, once heketi gets a request (create or delete) it will either return success or failure (eventually). Which is why I am wondering if we need to look at the provisioner rather than heketi directly (its not just laziness I swear :-)).

I'd also point out that 64 in flight operations is very high and and I don't know if you are going to get a lot of benefit from a value like that unless you have a lot of nodes. Ultimately, the operations are also bottlenecked at the ability to run commands on the nodes and allowing that many operations to run at once may actually hurt your  overall throughput. That's something you'd need to measure and experiment with on your set up though.

**Comment by amgads** [comment]
Thanks John for your quick response and feedback. So you want me to do something like

# kubectl exec <heketi-pod> -- heketi-cli volume create ?? 

In a shell script, with a loop. The do delete same way and see if we get the same issue. right?

**Comment by phlogistonjohn** [comment]
Yes. That's the case. Are you still experiencing problems in this area or are we safe to close this issue?

**Comment by amgads** [comment]
We wanted the application to do it in their environment, but they were busy for delivery.  We had another case with another application. So we'going to test that. Should provide you with data soon

**Comment by phlogistonjohn** [comment]
Fairly, stale issue. If you can still reproduce the problem on Heketi v10.0.0 or later, feel free to reopen this issue.
