### ISSUE TITLE
Timers for deleting devices

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1693]
Application as it tries to recover a node it invokes, delete devices, delete node.
We experience failure (K8S) as volumes are takine log time (many of them)
Is there a configurable timer to tune for the wait?

I see "gluster_cli_timeout" in heketi.json:
"gluster_cli_timeout": "Optional: Timeout, in seconds, passed to the gluster cli invocations",

Is it for handling such a situation? what's the default? 
And if yes, do we need to add it in both ""sshexec" and "kubeexec" sections?

Appreciate your answer!

**Comment by phlogistonjohn** [comment]
We've never needed to tune that option, to the best of my knowledge. I suspect you need to look into something deeper within your stack, probably starting with gluster/glusterd.
Since its been over a month since this was filed please let us know if you are no longer experiencing this issue so that we can close it.

**Comment by phlogistonjohn** [comment]
A bit of a stale issue. If you still experience this on v10 or later you can reopen this issue.

**Comment by amgads** [comment]
Sure -- Agreed
