### ISSUE TITLE
Heketi didn't recreate replicated bricks for volume when replacing a node.

### ISSUE THREAD

**Issue by jphuc96** [heketi/heketi#1706]
### Kind of issue
I don't know if it's bug or a new feature.

### Observed behavior
Heketi didn't recreate replicated bricks for volume when replacing a node.

### Expected/desired behavior
Heketi should automatically create bricks for the volume when replacing a node.

### Details on how to reproduce (minimal and precise)
I have 3 node with replica 3 for my volumes, which means each node has 1 brick for the volume. 

When 1 node down and I replace the node with the same IP by using heketi (remove and add the node again), heketi won't create bricks for the volumes on the new node.

I have to manually create bricks by gluster command.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v9.0.0
- Operating system used: Centos
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: heketi/heketi:latest
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): gk-deploy

**Comment by phlogistonjohn** [comment]
If you had three nodes with replica-3 volumes and you tried to remove the devices on a bad node, I would expect that it would (initially) fail because it has nowhere to put the replacement bricks.
Normally, you'd need to add an additional node and then you'd be able to remove the devices and node.

Thus the steps you've outlined so far don't make much sense to me. I think we need a more detailed list of steps that you took to understand what happened.

**Comment by phlogistonjohn** [comment]
Stale issue. If you can still reproduce the problem on Heketi v10.0.0 or later, feel free to reopen this issue.
