### ISSUE TITLE
Remove unexisting bricks from heketi database

### ISSUE THREAD

**Issue by nike38rus** [heketi/heketi#1723]
I've removed brick set from distribute-replicate gluster volume using this manual: https://docs.gluster.org/en/latest/Administrator%20Guide/Managing%20Volumes/#shrinking-volumes
Now I have inconsistent cluster topology in heketi DB (there's bricks in cluster topology that I've removed by hands). How can I sync heketi with current cluster state? Is there any other method to remove bricks from gluster volume using more heketi-native way to avoid such situations in future?

**Comment by iamniting** [comment]
Hi nike38rus,

We don't have such feature in heketi.

**Comment by nike38rus** [comment]
> Hi nike38rus,
> 
> We don't have such feature in heketi.

Yep, I've got that already :) 

can you recommend me some way to sync heketi db with current cluster state?

**Comment by iamniting** [comment]
you can sync your gluster with heketi via adding the same bricks in gluster vol again.

**Comment by nike38rus** [comment]
Is there any other options?

**Comment by iamniting** [comment]
Maybe, But I am not aware.

**Comment by phlogistonjohn** [comment]
Unfortunately, I think the only think you may have an option to try is to export the heketi db to json (while heketi is not running) and then edit the db to match your needs. I *highly* recommend trying it out on a scratch system before doing it in production. Because this is pretty involved there's not much support we can provide for this action. It's a bit on the "use the source luke" side of things, I'm sorry to say.

Because of the above and the age of this issue I'm going to close it. However, if you can questions about the above we can try to answer them to the best of our ability and available time. Thanks for your patience.
