### ISSUE TITLE
Loss of /var/lib/heketi.db - Import How

### ISSUE THREAD

**Issue by amehub** [heketi/heketi#1731]
### Kind of issue

Feature request

Testing operational procedures if I lose my heketi.db and how do I reinstate my heketi,db and logical volumes to the state before I removed the heketi.db.

### Observed behavior
On bare metal gluster cluster if I lose the heketi.db database file, restart heketi service, reload the /etc/heketi/topology.json file I now have a new heketi.db file and a cluster with no disk devices. "load topology" reports that the disk devices already contain physical volumes and heketi does not reinitilaize the disk devices.    The logical volumes all still exist. 

### Expected/desired behavior
Behaves as expected.

### Details on how to reproduce (minimal and precise)
systemctl stop heketi
rm /var/lib/heketi/heketi.db
systemctl start heketi
heketi-cli topology load --json=/etc/heketi/topology.json 

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
v9.0.0-137
- Operating system used:
Ubuntu 18.04 
- Heketi compiled from sources, as a package (rpm/deb), or container: 

- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information
How do I import the logical volumes into the heketi.db in order to restore heketi.db to the state it was in before I removed the heketi.db?  If this is not possible I would like to  make it a  feature request.

**Comment by iamniting** [comment]
You have to create a JSON (like topology file) manually and you can convert that JSON to heketi.db file via heketi.

e.g. https://github.com/heketi/heketi/blob/master/main.go#L84

**Comment by amehub** [comment]
Thanks,  Are there any example topology files for importing all the existing logical volumes to heketi.db?  It would be nice if heketi just read the /etc/heketi/topology.json file and all the mounts under /var/lib/heketi/mounts and reconstructed the heketi.db file in order to recover the heketi.db state if the heketi.db got lost.

**Comment by phlogistonjohn** [comment]
Sorry, you can not reinitialize the db from an existing cluster. We have no plans on implementing this feature.

Two alternatives that you can do is to:
* export the db and/or otherwise back the db up; then if there is a catastrophic loss of the server you can restore the db. An issue with this technique is that you could lose state between the backup occurring and state change on the storage nodes followed by a loss of the db.
* store the db on replicated storage, such as gluster itself. This technique is commonly used in kubernetes/openshift when heketi is run as a pod. There's a little bootstrapping dance that needs to be done by which heketi runs on local storage, then is asked to create a volume for the db, and then the db is moved over to this volume. Refer to either the gluster-kubernetes project or openshift-ansbile for examples of how this is done.

**Comment by amehub** [comment]
Thanks for the reply.  I have been testing the export and import today and that works very well.   I need to consider the frequency of exports to minimise the state change in the event a restore is required.

**Comment by phlogistonjohn** [comment]
I hope my answer helped, as there's been no updates for over a month and v10 is now out I'm closing this issue. However, if you continue to have problems in this are feel free to reopen as needed.
