### ISSUE TITLE
Incorrect Heketi version displayed for v10.0.0

### ISSUE THREAD

**Issue by sangitanalkar** [heketi/heketi#1761]
### Kind of issue
> Bug

### Observed behavior
When heketi is built from source for tag `v10.0.0`, heketi version displayed is `Heketi v9.0.0-208-gdf2ce1f4-HEAD`
```
# ./heketi --version
Heketi v9.0.0-208-gdf2ce1f4-HEAD
```

### Expected/desired behavior
When heketi is built from from source for tag `v10.0.0`, heketi version displayed should be v10.0.0

### Details on how to reproduce (minimal and precise)
Build heketi from source for tag `v10.0.0`

### Information about the environment:

- Heketi version used : v10.0.0
- Operating system used: x86 
- Heketi compiled from sources, as a package (rpm/deb), or container: compiled from source

### Fix needed
Need to add `v[0-9]*` as following in [Makefile](https://github.com/heketi/heketi/blob/v10.0.0/Makefile) and [cli-Makefile](https://github.com/heketi/heketi/blob/v10.0.0/client/cli/go/Makefile)
```
VER := $(shell git describe --match='v[0-9]*.[0-9].[0-9]')
TAG := $(shell git tag --points-at HEAD 'v[0-9]*.[0-9].[0-9]' | tail -n1)
```

### Additional information
Would request to please add the fix for v10.0.0

**Comment by iamniting** [comment]
Hi @sangitanalkar we are aware of this issue, we already have a fix merged in master. We will get it fixed soon.

**Comment by phlogistonjohn** [comment]
Unfortunately, the v10.0.0 tag is wrong and it will remain wrong as I don't expect to alter the tag. There are fixes for this issue in both master, as @iamniting mentioned, and the release/10 branch. We've already fixed a regression in in patches that is present in v10 and I fully expect to do another release at some point soonish.
For now, I suggest building from release/10 rather than the v10.0.0 tag as that branch has the build fixes but no server or client code differences from the tag.

**Comment by sangitanalkar** [comment]
Sure. Thanks @iamniting and @phlogistonjohn for responding. Closing this issue.
