### ISSUE TITLE
Device State output is not same as when using json

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1801]
### Kind of issue
Bug

### Observed behavior
When running device info, the State field value is "removed" and the key is "State" with capital "S"
while when using --json, the value is "failed" and the key is "state" with lower case "s"

bash-4.4# heketi_cli.py device info 32167f65f0e3fbaa03d28e755f23c7ac
Device Id: 32167f65f0e3fbaa03d28e755f23c7ac
State: removed
Size (GiB): 24
Used (GiB): 0
Free (GiB): 24
Create Path: /dev/vdd
Physical Volume UUID: za2Wp9-cbfr-sg01-4JOr-57mN-NNB8-RRq4zs
Known Paths: /dev/vdd
Bricks:

bash-4.4# heketi_cli.py device info 32167f65f0e3fbaa03d28e755f23c7ac --json
{"name":"/dev/vdd","storage":{"total":26079232,"free":26079232,"used":0},"id":"32167f65f0e3fbaa03d28e755f23c7ac","paths":["/dev/vdd"],"pv_uuid":"za2Wp9-cbfr-sg01-4JOr-57mN-NNB8-RRq4zs","state":"failed","bricks":[]}
bash-4.4# 

### Expected/desired behavior
Field name and value should be the same, whether the output is raw or in json format

### Details on how to reproduce (minimal and precise)
run heketi-cli device info <device-id>
And
run heketi-cli device info <device-id> --json

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v10.1.0
- Operating system used: CentOS8
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: custom
- Using kubernetes, openshift, or direct install:  k8s
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside on VMs
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): other

**Comment by iamniting** [comment]
You are seeing two different things, but in actual they are not different. In JSON format client directly prints the response from the server otherwise, the heketi-client will format the string in its own way. Which you can see in [1] and [2].

If you are using wrappers around it I would recommend you use JSON as you can parse it very easily and show it in your own way. even though you can create your own API client as well.

[1] https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/device.go#L239
[2] https://github.com/heketi/heketi/blob/master/client/cli/go/cmds/utils.go#L115

**Comment by phlogistonjohn** [comment]
Sorry but as @iamniting points out when you use the json flag you are seeing  the server's raw response, while the other output is processed by the cli tool. The cli tool was changed to be more "user friendly" in the past. Neither it nor the JSON response will be changed at this point.
