### ISSUE TITLE
Heketi v10.1 broke db backward compatibility with previous releases (v9) and prevents rollback

### ISSUE THREAD

**Issue by amgads** [heketi/heketi#1803]
### Kind of issue
Bug

### Observed behavior
When we upgrade the system from heketi v9.0.0 (container) to heketi v10.1.0, heketi container comes up with no issues

Rolling back to v9.0.0, heketi crashes with the following messages:
---
2020-11-13T03:26:22.844Z heketi-fb855979-wb49z.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-12 21:26:22,843 INFO spawned: 'heketi' with pid 365
2020-11-13T03:26:22.934Z heketi-fb855979-wb49z.ncms docker_entrypoint.sh heketi: LOG:info Heketi v9.0.0
2020-11-13T03:26:22.940Z heketi-fb855979-wb49z.ncms docker_entrypoint.sh heketi: LOG:info [heketi] ERROR 2020/11/12 21:26:22 heketi/apps/glusterfs/dbattribute_entry.go:103:glusterfs.validDbAttributeKeys: unknown dbattribute key: DB_DEVICE_HAS_ID_META
2020-11-13T03:26:22.940Z heketi-fb855979-wb49z.ncms docker_entrypoint.sh heketi: LOG:info [heketi] ERROR 2020/11/12 21:26:22 heketi/apps/glusterfs/app.go:226:glusterfs.(*App).initDB.func1: Unable to initialize db, unknown attributes are present (db from a newer version of heketi?)
2020-11-13T03:26:22.940Z heketi-fb855979-wb49z.ncms docker_entrypoint.sh heketi: LOG:info [heketi] ERROR 2020/11/12 21:26:22 heketi/apps/glusterfs/app.go:170:glusterfs.(*App).setup: Unable to initialize db, unknown attributes are present (db from a newer version of heketi?)
2020-11-13T03:26:22.940Z heketi-fb855979-wb49z.ncms docker_entrypoint.sh heketi: LOG:info ERROR: Unable to start application: Unable to initialize db, unknown attributes are present (db from a newer version of heketi?)
2020-11-13T03:26:22.944Z heketi-fb855979-wb49z.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-12 21:26:22,943 INFO exited: heketi (exit status 1; not expected)
2020-11-13T03:26:23.948Z heketi-fb855979-wb49z.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-12 21:26:23,945 INFO gave up: heketi entered FATAL state, too many start retries too quickly
---
The difference between the v9 db before the upgrade (with no volumes created) and v10 after upgrade shows:
<         "DB_DEVICE_HAS_ID_META": {
<             "Key": "DB_DEVICE_HAS_ID_META",
<             "Value": "yes"
<         },

which has the new attribute. 
If try to dump db after the rollback before it crashes, I get - the followig in el7 env:

Error: Get http://10.254.0.101:8080/db/dump: dial tcp 10.254.0.101:8080: getsockopt: connection refused
in el8 env, it hangs. 

db check is same before/after upgrade. After rolling back can't get it.

"db dump" v9 prior upgrade:
========================
{
    "clusterentries": {
        "c9bd1e306356ae2cee9a067644ae49a3": {
            "Info": {
                "id": "c9bd1e306356ae2cee9a067644ae49a3",
                "nodes": [
                    "2bfc8f88d4c59c9f761236729b0786ca",
                    "8508b97e3f8758f7871433ebbe604f99",
                    "c6803ec306900d4ce89ddcab2b2e10af"
                ],
                "volumes": [],
                "block": true,
                "file": true,
                "blockvolumes": []
            }
        }
    },
    "volumeentries": {},
    "brickentries": {},
    "nodeentries": {
        "2bfc8f88d4c59c9f761236729b0786ca": {
            "State": "online",
            "Info": {
                "zone": 1,
                "hostnames": {
                    "manage": [
                        "csto-bcmt-2006os8-control-01"
                    ],
                    "storage": [
                        "172.16.1.8"
                    ]
                },
                "cluster": "c9bd1e306356ae2cee9a067644ae49a3",
                "id": "2bfc8f88d4c59c9f761236729b0786ca"
            },
            "Devices": [
                "896e187bba42bd38036ec00ffad01e2f"
            ]
        },
        "8508b97e3f8758f7871433ebbe604f99": {
            "State": "online",
            "Info": {
                "zone": 1,
                "hostnames": {
                    "manage": [
                        "csto-bcmt-2006os8-control-02"
                    ],
                    "storage": [
                        "172.16.1.11"
                    ]
                },
                "cluster": "c9bd1e306356ae2cee9a067644ae49a3",
                "id": "8508b97e3f8758f7871433ebbe604f99"
            },
            "Devices": [
                "f3634e84d82c304aa577e36d2c2b7194"
            ]
        },
        "c6803ec306900d4ce89ddcab2b2e10af": {
            "State": "online",
            "Info": {
                "zone": 1,
                "hostnames": {
                    "manage": [
                        "csto-bcmt-2006os8-control-03"
                    ],
                    "storage": [
                        "172.16.1.5"
                    ]
                },
                "cluster": "c9bd1e306356ae2cee9a067644ae49a3",
                "id": "c6803ec306900d4ce89ddcab2b2e10af"
            },
            "Devices": [
                "89b947237dd1f4e5e839967a7377ab1b"
            ]
        }
    },
    "deviceentries": {
        "896e187bba42bd38036ec00ffad01e2f": {
            "State": "online",
            "Info": {
                "name": "/dev/vdd",
                "storage": {
                    "total": 26079232,
                    "free": 26079232,
                    "used": 0
                },
                "id": "896e187bba42bd38036ec00ffad01e2f"
            },
            "Bricks": [],
            "NodeId": "2bfc8f88d4c59c9f761236729b0786ca",
            "ExtentSize": 4096
        },
        "89b947237dd1f4e5e839967a7377ab1b": {
            "State": "online",
            "Info": {
                "name": "/dev/vdd",
                "storage": {
                    "total": 26079232,
                    "free": 26079232,
                    "used": 0
                },
                "id": "89b947237dd1f4e5e839967a7377ab1b"
            },
            "Bricks": [],
            "NodeId": "c6803ec306900d4ce89ddcab2b2e10af",
            "ExtentSize": 4096
        },
        "f3634e84d82c304aa577e36d2c2b7194": {
            "State": "online",
            "Info": {
                "name": "/dev/vdd",
                "storage": {
                    "total": 26079232,
                    "free": 26079232,
                    "used": 0
                },
                "id": "f3634e84d82c304aa577e36d2c2b7194"
            },
            "Bricks": [],
            "NodeId": "8508b97e3f8758f7871433ebbe604f99",
            "ExtentSize": 4096
        }
    },
    "blockvolumeentries": {},
    "dbattributeentries": {
        "DB_BRICK_HAS_SUBTYPE_FIELD": {
            "Key": "DB_BRICK_HAS_SUBTYPE_FIELD",
            "Value": "yes"
        },
        "DB_CLUSTER_HAS_FILE_BLOCK_FLAG": {
            "Key": "DB_CLUSTER_HAS_FILE_BLOCK_FLAG",
            "Value": "yes"
        },
        "DB_GENERATION_ID": {
            "Key": "DB_GENERATION_ID",
            "Value": "1244318b38f31dcd96499f122dd99913"
        },
        "DB_HAS_PENDING_OPS_BUCKET": {
            "Key": "DB_HAS_PENDING_OPS_BUCKET",
            "Value": "yes"
        }
    },
    "pendingoperations": {}
}

"db dump" v10.1 after upgrade:
==========================
{
    "clusterentries": {
        "c9bd1e306356ae2cee9a067644ae49a3": {
            "Info": {
                "id": "c9bd1e306356ae2cee9a067644ae49a3",
                "nodes": [
                    "2bfc8f88d4c59c9f761236729b0786ca",
                    "8508b97e3f8758f7871433ebbe604f99",
                    "c6803ec306900d4ce89ddcab2b2e10af"
                ],
                "volumes": [],
                "block": true,
                "file": true,
                "blockvolumes": []
            }
        }
    },
    "volumeentries": {},
    "brickentries": {},
    "nodeentries": {
        "2bfc8f88d4c59c9f761236729b0786ca": {
            "State": "online",
            "Info": {
                "zone": 1,
                "hostnames": {
                    "manage": [
                        "csto-bcmt-2006os8-control-01"
                    ],
                    "storage": [
                        "172.16.1.8"
                    ]
                },
                "cluster": "c9bd1e306356ae2cee9a067644ae49a3",
                "id": "2bfc8f88d4c59c9f761236729b0786ca"
            },
            "Devices": [
                "896e187bba42bd38036ec00ffad01e2f"
            ]
        },
        "8508b97e3f8758f7871433ebbe604f99": {
            "State": "online",
            "Info": {
                "zone": 1,
                "hostnames": {
                    "manage": [
                        "csto-bcmt-2006os8-control-02"
                    ],
                    "storage": [
                        "172.16.1.11"
                    ]
                },
                "cluster": "c9bd1e306356ae2cee9a067644ae49a3",
                "id": "8508b97e3f8758f7871433ebbe604f99"
            },
            "Devices": [
                "f3634e84d82c304aa577e36d2c2b7194"
            ]
        },
        "c6803ec306900d4ce89ddcab2b2e10af": {
            "State": "online",
            "Info": {
                "zone": 1,
                "hostnames": {
                    "manage": [
                        "csto-bcmt-2006os8-control-03"
                    ],
                    "storage": [
                        "172.16.1.5"
                    ]
                },
                "cluster": "c9bd1e306356ae2cee9a067644ae49a3",
                "id": "c6803ec306900d4ce89ddcab2b2e10af"
            },
            "Devices": [
                "89b947237dd1f4e5e839967a7377ab1b"
            ]
        }
    },
    "deviceentries": {
        "896e187bba42bd38036ec00ffad01e2f": {
            "State": "online",
            "Info": {
                "name": "/dev/vdd",
                "storage": {
                    "total": 26079232,
                    "free": 26079232,
                    "used": 0
                },
                "id": "896e187bba42bd38036ec00ffad01e2f"
            },
            "Bricks": [],
            "NodeId": "2bfc8f88d4c59c9f761236729b0786ca",
            "ExtentSize": 4096
        },
        "89b947237dd1f4e5e839967a7377ab1b": {
            "State": "online",
            "Info": {
                "name": "/dev/vdd",
                "storage": {
                    "total": 26079232,
                    "free": 26079232,
                    "used": 0
                },
                "id": "89b947237dd1f4e5e839967a7377ab1b"
            },
            "Bricks": [],
            "NodeId": "c6803ec306900d4ce89ddcab2b2e10af",
            "ExtentSize": 4096
        },
        "f3634e84d82c304aa577e36d2c2b7194": {
            "State": "online",
            "Info": {
                "name": "/dev/vdd",
                "storage": {
                    "total": 26079232,
                    "free": 26079232,
                    "used": 0
                },
                "id": "f3634e84d82c304aa577e36d2c2b7194"
            },
            "Bricks": [],
            "NodeId": "8508b97e3f8758f7871433ebbe604f99",
            "ExtentSize": 4096
        }
    },
    "blockvolumeentries": {},
    "dbattributeentries": {
        "DB_BRICK_HAS_SUBTYPE_FIELD": {
            "Key": "DB_BRICK_HAS_SUBTYPE_FIELD",
            "Value": "yes"
        },
        "DB_CLUSTER_HAS_FILE_BLOCK_FLAG": {
            "Key": "DB_CLUSTER_HAS_FILE_BLOCK_FLAG",
            "Value": "yes"
        },
        "DB_DEVICE_HAS_ID_META": {
            "Key": "DB_DEVICE_HAS_ID_META",
            "Value": "yes"
        },
        "DB_GENERATION_ID": {
            "Key": "DB_GENERATION_ID",
            "Value": "1244318b38f31dcd96499f122dd99913"
        },
        "DB_HAS_PENDING_OPS_BUCKET": {
            "Key": "DB_HAS_PENDING_OPS_BUCKET",
            "Value": "yes"
        }
    },
    "pendingoperations": {}
}

### Expected/desired behavior
Should be able to upgrade and rollback without issues, this was the case for all previous heketi releases -- it's also a requirement by all customers (in particular all our tier-1 customers) in case the system has an issue - and what's meant by the system here, the one running all infra-structures and applications in k8s, including heketi. Can't afford re-install.

Is there a way to avoid this? Help for resolution is highly appreciated!

### Details on how to reproduce (minimal and precise)
1) install heketi v9 (container) / glusterin k8s enviroment
2) upgrade to heketi 10
3) rollout the heketi deployment to v9

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v10.1.0
- Operating system used: CentOS8/CentOS7
- Heketi compiled from sources, as a package (rpm/deb), or container: container
- If container, which container image: built using the tarball
- Using kubernetes, openshift, or direct install:  k8s
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside on VMs
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): other

**Comment by amgads** [comment]
log from starting the rollout container to failure (it continues to fail till crash)
2020-11-13T01:48:44.177Z heketi-595f7bfd97-rjhj5.ncms harmonize_log heketi: LOG:info Creating log file /var/log/hmanager.log
2020-11-13T01:48:44.182Z heketi-595f7bfd97-rjhj5.ncms harmonize_log heketi: LOG:info Creating log file /var/log/heketi_cli.log
2020-11-13T01:48:44.187Z heketi-595f7bfd97-rjhj5.ncms harmonize_log heketi: LOG:info Creating log file /var/log/hconfig.log
2020-11-13T01:48:44.397Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:44,395 CRIT Supervisor running as root (no user in config file)
2020-11-13T01:48:44.399Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:44,395 WARN No file matches via include "/etc/supervisord.d/*.ini"
2020-11-13T01:48:44.400Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:44,395 WARN For [program:heketi], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2020-11-13T01:48:44.400Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:44,395 WARN For [program:hmanager], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2020-11-13T01:48:44.411Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:44,411 INFO RPC interface 'supervisor' initialized
2020-11-13T01:48:44.412Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:44,411 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-11-13T01:48:44.415Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:44,412 INFO supervisord started with pid 7
2020-11-13T01:48:45.416Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:45,415 INFO spawned: 'heketi' with pid 25
2020-11-13T01:48:45.418Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:45,417 INFO spawned: 'hmanager' with pid 26
2020-11-13T01:48:45.473Z heketi-595f7bfd97-rjhj5.ncms hmanager.py heketi: LOG:info Heketi health monitor service started
2020-11-13T01:48:45.553Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info Heketi v9.0.0
2020-11-13T01:48:45.560Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info [heketi] ERROR 2020/11/13 09:48:45 heketi/apps/glusterfs/dbattribute_entry.go:103:glusterfs.validDbAttributeKeys: unknown dbattribute key: DB_DEVICE_HAS_ID_META
2020-11-13T01:48:45.561Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info [heketi] ERROR 2020/11/13 09:48:45 heketi/apps/glusterfs/app.go:226:glusterfs.(*App).initDB.func1: Unable to initialize db, unknown attributes are present (db from a newer version of heketi?)
2020-11-13T01:48:45.561Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info [heketi] ERROR 2020/11/13 09:48:45 heketi/apps/glusterfs/app.go:170:glusterfs.(*App).setup: Unable to initialize db, unknown attributes are present (db from a newer version of heketi?)
2020-11-13T01:48:45.562Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info ERROR: Unable to start application: Unable to initialize db, unknown attributes are present (db from a newer version of heketi?)
2020-11-13T01:48:45.564Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:45,563 INFO exited: heketi (exit status 1; not expected)
2020-11-13T01:48:45.473Z heketi-595f7bfd97-rjhj5.ncms hmanager.py heketi: LOG:info Heketi health monitor service started
2020-11-13T01:48:46.568Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:46,567 INFO spawned: 'heketi' with pid 34
2020-11-13T01:48:46.568Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:46,568 INFO success: hmanager entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-13T01:48:46.640Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info Heketi v9.0.0
2020-11-13T01:48:46.650Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info [heketi] ERROR 2020/11/13 09:48:46 heketi/apps/glusterfs/dbattribute_entry.go:103:glusterfs.validDbAttributeKeys: unknown dbattribute key: DB_DEVICE_HAS_ID_META
2020-11-13T01:48:46.650Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info [heketi] ERROR 2020/11/13 09:48:46 heketi/apps/glusterfs/app.go:226:glusterfs.(*App).initDB.func1: Unable to initialize db, unknown attributes are present (db from a newer version of heketi?)
2020-11-13T01:48:46.650Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info [heketi] ERROR 2020/11/13 09:48:46 heketi/apps/glusterfs/app.go:170:glusterfs.(*App).setup: Unable to initialize db, unknown attributes are present (db from a newer version of heketi?)
2020-11-13T01:48:46.651Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info ERROR: Unable to start application: Unable to initialize db, unknown attributes are present (db from a newer version of heketi?)
2020-11-13T01:48:46.661Z heketi-595f7bfd97-rjhj5.ncms docker_entrypoint.sh heketi: LOG:info 2020-11-13 09:48:46,661 INFO exited: heketi (exit status 1; not expected)

**Comment by amgads** [comment]
I guess the question becomes is there a way when revert to v9, to exclude the additional attribute? something to maintain the compatibility

**Comment by phlogistonjohn** [comment]
Rolling back to older versions has never been supported and will never be supported. We took care in previous versions to make this clearer by triggering an explicit error early in the start up process, which you are seeing.

**Comment by amgads** [comment]
Hi John -- rollback was working for previous versions. v10.1 makes everything a disaster recovery!!
But for this particular situation, would you mind help answering the following:
1) Is there a way thru the config file, for instance not to include the attribute DB_DEVICE_HAS_ID_META in the DB? 
2) If not, for disaster recovery:
          - I tried to copy heketi.db file to heketi.db.bk during upgrade and then flip it when rolling back. It worked without any volumes, just the topology. If there are many volumes, etc would it be a problem?
          - what is the safest way to do the backup or when copying heketi.db to heketi.db.bk? is there a way to make the file 
            consistent when backing it up or copied to .bk version. Something like making sure no transactions in progress and maybe stopped (the deploy is in a container)

Your support is highly appreciated!!

**Comment by phlogistonjohn** [comment]
> Hi John -- rollback was working for previous versions. v10.1 makes everything a disaster recovery!!

You must have been getting rather lucky. It was never supported/an actual feature, it was simply that older versions didn't check anything at start-up time and simply assumed the db contents matched its "schema". To be frank, sometimes new versions don't make any change to how data is stored in the db. Because of this, and other reasons, the compatibility checking is based on db content not version numbers. Thus, you might find it possible to toggle back and forth between 10.0 and 10.1 (I have not actually checked this... its supposition based on my admittedly faulty memory). However when something major in the db changes now we add a flag. Recent-ish versions of heketi make sure the db doesn't contain any flags it does not understand, so that it can not lose or corrupt any of the new-style data structures.

I'm not sure what you mean by "disaster recovery" in this context. 


> But for this particular situation, would you mind help answering the following:
> 
>     1. Is there a way thru the config file, for instance not to include the attribute DB_DEVICE_HAS_ID_META in the DB?
> 

No there is not. Even if we had a feature to disallow certain behaviors (and block adding the flag) in the db, this one would not be included. The previous way heketi used to track devices in the db was very flawed and this new metadata is meant to help fix that flaw.



>     2. If not, for disaster recovery:
>        - I tried to copy heketi.db file to heketi.db.bk during upgrade and then flip it when rolling back. It worked without any volumes, just the topology. If there are many volumes, etc would it be a problem?

To be clear: you are taking a copy of the db file, while heketi is not running to act as a snapshot and then after running a newer version of heketi, reverting both the db file and the heketi binary to older instances.
If that is all correct, then it is only a problem if you actually add/change/delete anything in the newer instance. Because if you roll back to an older copy of the db you will lose all those changes. In other words, it might "work" in theory but be rather impractical as the point of heketi is to serve as a system to centralize the management of the gluster clusters and the backing devices and so, IMO, change is essential.

That all said, I strongly support taking backups of the db before making major changes to the system. I would simply plan on not reverting to the snapshot with an older version and expect everything to work.

>        - what is the safest way to do the backup or when copying heketi.db to heketi.db.bk? is there a way to make the file
>        consistent when backing it up or copied to .bk version. Something like making sure no transactions in progress and maybe stopped (the deploy is in a container)

Indeed. First off, never copy the heketi db file while heketi is active and running. Doing so could lead to a "corrupt" db file copy. This has to do with the nature of the db file format. It is safe to copy the db file when heketi is not running. 

Newer version of the heketi container start up script try to "automatically" take snapshots of the db using the json export feature. If the container is the image we provide at dockerhub you should may an archive directory in the same path as the db. This contains json snapshots taken before the heketi server process starts. This can be copied out of said directory at any time.

Using the heketi api you can get similar json "dumps" at any time. This can be done using the `db dump` subcommand. This is not as good as taking the db file or json exports when heketi is off as you can catch the server mid operation. It is db safe though as the dump is performed in a read transaction at the db level. You can ensure a db dump that is not in the midst of an operation by the following:
* put the server in "administrative" mode - using the `server mode set` subcommand and, depending on your situation using either local-only or read-only modes (see blow for an important caveat)
* poll the server for "in flight" operations - using the `server operations info` subcommand
* once the number drops to zero heketi is no longer working on any operations, and the administrative mode prevents new ones from being added
* take a live db dump
* Put heketi back in normal mode:
** If heketi is in local-only mode you can use `server mode set` again, but ONLY if heketi-cli communicating with the server over the localhost IP address
** Send the heketi server process a SIGUSR2 signal.  No matter what other mode heketi is in this signal sets it back to normal mode

Due to the number of steps it may be a lot simpler to just stop heketi. On the other hand, heketi will continue to take read-only requests, so things like prometheus metrics continue to work w/o downtime.


To wrap it all up: rolling back to an old version is never a good idea. If it worked for you before it was entirely by accident. You can take copies or dumps of the DB for backup/DR purposes. When doing a disaster recovery you should use a version of heketi equal to or greater than the version that the db was taken from. If heketi makes changes to the nodes or gluster system
it front-ends, and you need to restore from snapshot you may have issues where gluster and the nodes are not in sync with heketi. This kind of discrepancy can only be resolved manually - I prefer deleting out-of-sync items if I can - but must be done on a case-by-case basis and is typically a very tedious process, so avoid it if you can.

**Comment by amgads** [comment]
Thanks a lot John for the detailed answers. We only rollback within a maintenance window where upgrade is executed. If any issue happens with any of the system element (not necessarily "heketi". But sure once upgrade is successful, things move forward. Also regular recovery uses whatever version was on the system.
Two clarifications:
1) what is the difference between the "local-only" and " read-only"?
2) After putting the system in administrative mode and the In Flight count goes to "0", is the "live db dump" equivalent to copy the db file to a backup version?

**Comment by phlogistonjohn** [comment]
>     1. what is the difference between the "local-only" and " read-only"?
> 

Apologies, I wrote that from memory and the mode is actually "local-client" _not_ "local-only". The CLI --help for `heketi-cli server mode set` will show the correct examples.

The "local-client" option tells the client to only accept commands that make changes from localhost (127.0.0.1). IOW, it only allows commands to come from the local system and not another host on the network.

The "read-only" mode does roughly what it says. The heketi server only services API requests that don't make any changes to the system (that includes `server mode set`).


>     2. After putting the system in administrative mode and the In Flight count goes to "0", is the "live db dump" equivalent to copy the db file to a backup version?
>        By dump, you mean "heketi db export" to a file? I know the db file is binary.

No, its a JSON representation of the db.
The commands `heketi-cli db dump` and `heketi db export` both emit the same sort of JSON representation of the db contents. The former talks to the server and gets the json from the running heketi instance. The latter operates directly on the binary boltdb file.

The command `heketi db import` can create a binary boltdb file from the JSON. 

Do note the command names above: `heketi` is the same binary used to start the server while `heketi-cli` is a command that communicates with an existing running server.

Do note that the JSON format is beholden to the same versioning rules as I mentioned before. That's because it's the db contents, not the key-value store of boltdb that is important to heketi. The plus side of the json is that it compresses well and can be easily analyzed offline.

**Comment by amgads** [comment]
Thanks John -- I guess a follow-up question - We use ansible scripts to upgrade/rollback, so if I
    1) dump the database before upgrade from v9 to v10:
          heketi_cli.py db dump --json > /tmp/db9.json
    2) Import the file to a binary format
          heketi db import --dbfile=/var/lib/heketi/h9.db --jsonfile=/tmp/db9.json
    3) Do upgrade from v9 to v10 --> the database file is /var/lib/heketi/heketi.db

Then, when doing rollback, I'll
    1) replace the heketi.db file by the h9.db, and rollback.

My follow-up question, is h9.db same as the original db file in v9 before upgrade? The reason I'm asking, when doing steps 1) and 2) before the upgrade, the h9.db size seems to be smaller than the working v9 heketi.db file.

In another word, even if I'm not doing upgrade/rollback, if h9.db is a snapshot backup, is it valid for recovery of the same version? and if yes, why it's smaller in size on disk compared to the running version.

# ls -ltr /opt/bcmt/storage/*.db
-rw-------. 1 root root  **65536** Nov 14 02:00 /opt/bcmt/storage/**h9.db**
-rw-------. 1 root root **131072** Nov 14 06:11 /opt/bcmt/storage/**heketi.db**

**Comment by amgads** [comment]
HI John:
I tried the following and it seems to work -- any concerns, especially in 2.e? should I better stop the service completely before that step? Also would it better to use "mv /var/lib/heketi/heketi.db.restore /var/lib/heketi/heketi.db"
1) Before upgrade to v10.1
          a. heketi_cli.py server mode set read-only
          b. Check Check In-Flight operations till number is '0'
              nops=$(/usr/bin/heketi_cli.py server operations info | grep 'In-Flight' | awk '{ print $2 }')
          c. dump the database into a json file
             /usr/bin/heketi_cli.py db dump > /tmp/db.json
          d. import the json file into a backup db file
             /usr/bin/heketi db import --dbfile=/var/lib/heketi/heketi.db.restore --jsonfile=/tmp/db.json
         e. Perform pgarde
2) when rollback to v9 if have to
          a. /usr/bin/heketi_cli.py db dump > /tmp/db.json
          b. Check Check In-Flight operations till number is '0'
              nops=$(/usr/bin/heketi_cli.py server operations info | grep 'In-Flight' | awk '{ print $2 }')
          b. Check Check In-Flight operations till number is '0'
              nops=$(/usr/bin/heketi_cli.py server operations info | grep 'In-Flight' | awk '{ print $2 }')
          c. dump the database into a json file
             /usr/bin/heketi_cli.py db dump > /tmp/db.json
          d. import the json file into a backup db file --- mainly as a backup
             /usr/bin/heketi db import --dbfile=/var/lib/heketi/heketi.db.backup --jsonfile=/tmp/db.json
          e. cp /var/lib/heketi/heketi.db.restore /var/lib/heketi/heketi.db
          f. Perform rollback
