### ISSUE TITLE
Delete volume 404

### ISSUE THREAD

**Issue by iamruhua** [heketi/heketi#1813]
### Kind of issue
> Bug

### Observed behavior
Heketi is looping to delete some volumes that's not in the system forever.

[negroni] 2020-12-04T02:32:04Z | 404 |   164.218µs | heketi-storage.glusterfs.svc:8080 | DELETE /volumes/3bc969f98a3cba200fa3482e8da025eb
[negroni] 2020-12-04T02:32:04Z | 404 |   203.271µs | heketi-storage.glusterfs.svc:8080 | DELETE /volumes/062b61f55ee8d9d5a8e89abeabfd7cfa
[negroni] 2020-12-04T02:33:14Z | 200 |   170.017µs | localhost:8080 | GET /volumes
[negroni] 2020-12-04T02:33:14Z | 200 |   661.786µs | localhost:8080 | GET /volumes/0fa7c61ee4c4199ad17bb2156e0a48ac
[negroni] 2020-12-04T02:33:14Z | 200 |   642.098µs | localhost:8080 | GET /volumes/457618dcccd46f523a4c5e10137cd7bf
[negroni] 2020-12-04T02:33:14Z | 200 |   590.013µs | localhost:8080 | GET /volumes/51d7cdf85d62df46f738f04b61dd0d4b

### Expected/desired behavior
This should not happen

### Details on how to reproduce (minimal and precise)
I have seen similar bug report in redhat forum but I don't know how to exactly restore the heketi state.

### Information about the environment:

- Heketi version used 9.0.0-9.el7rhgs
- Operating system used: Redhat 7.6
- Using Openshift 3.11 default configuration

### Other useful information
Is there anyway to stop heketi from keep trying?
Maybe scale the heketi deployment to 0, remove the persistent storage of heketi and then scale to 1 to force recreate?

**Comment by iamniting** [comment]
There can be many reasons that heketi is trying to delete the same volume again and again. It is possible that OCP is sending a request to heketi to do so, because of some PVC that was deleted from heketi directly and now from OCP, But OCP will try again and again until success and heketi won't we able to succeed at all.

You should look at the operations list from heketi-client and need to debug why it is doing so.

**Comment by phlogistonjohn** [comment]
First off, I see 9.0.0-9.el7rhgs which is what I assume to be a Red Hat supplied RPM. That's not something the heketi project maintains. If you're using Red Hat products I suggest you contact Red Hat support for direct assistance. 


> There can be many reasons that heketi is trying to delete the same volume again and again. It is possible that OCP is sending a request to heketi to do so, because of some PVC that was deleted from heketi directly and now from OCP, But OCP will try again and again until success and heketi won't we able to succeed at all.

In short, yes. To be precise heketi is not looping, some client of heketi is. This is probably kube/openshift. It may be possible to delete the resources in k8s that is triggering this behavior.

> 
> You should look at the operations list from heketi-client and need to debug why it is doing so.

Unfortunately, you won't see anything in this case. If heketi returns a 404 for a resource there won't be an operation created because the server has already determined there's not matching resource.

To match up pvs/pvcs with heketi volumes you can dump all the pvs (`kubectl get pv -o yaml`, IIRC) and those pvs that were created via heketi should have heketi volume ids in there.

**Comment by iamruhua** [comment]
Helpful information
