### ISSUE TITLE
RPM package for v10

### ISSUE THREAD

**Issue by ThomasBuchinger** [heketi/heketi#1819]
I built RPM packages for version 10.

I used the spec-file from [this previous package](https://download.fedoraproject.org/pub/fedora/linux/releases/32/Everything/source/tree/Packages/h/heketi-9.0.0-5.fc32.src.rpm), which worked without modification. If some else is looking for >9.0.0  rpms

Link: https://copr.fedorainfracloud.org/coprs/thomasbuchinger/heketirpm/

**Comment by phlogistonjohn** [comment]
It's great that you have built a COPR for your heketi rpms. However, since the heketi project / maintenance team doesn't create these packages,  I don't see an open issue as an appropriate channel to share your creation with others. As such I'm going to close this issue. As alternatives I suggest mailing the heketi mailing list or perhaps using the heketi wiki. For the latter I would suggest a new page, that others could add to, called something like "Unofficial Builds" or something along those lines.

If you wish to further discuss on this topic the mailing list may be more appropriate. Thanks!
