### ISSUE TITLE
Replace github.com/form3tech-oss/jwt-go with https://github.com/golang-jwt/jwt

### ISSUE THREAD

**Issue by Haimantika** [heketi/heketi#1871]
### Kind of issue
> Bug

### Observed behavior
We have been using github.com/form3tech-oss/jwt-go, which now should be replaced with https://github.com/golang-jwt/jwt

### Details on how to reproduce (minimal and precise)
Since the maintained fork of https://github.com/form3tech-oss/jwt-go seems now to be https://github.com/golang-jwt/jwt, we might need to make some changes accordingly.  For more information on this please refer to kubernetes/kubernetes#104007

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by humblec** [comment]
@Haimantika would you like to send a PR for this change ? 

@phlogistonjohn @raghavendra-talur are you guys fine with this change ?

**Comment by Haimantika** [comment]
> @Haimantika would you like to send a PR for this change ?
> 
> @phlogistonjohn @raghavendra-talur are you guys fine with this change ?

https://github.com/heketi/heketi/pull/1872 PR link

**Comment by humblec** [comment]
> > @Haimantika would you like to send a PR for this change ?
> > @phlogistonjohn @raghavendra-talur are you guys fine with this change ?
> 
> #1872 PR link

Thanks :+1:

**Comment by phlogistonjohn** [comment]
Yes, I saw these. Please do note that heketi is very much in maintenance status and while we're dedicated to supporting it for some time, it's no-one's 100% and so responses may be delayed. I suggest folks shouldn't worry unless you see 2 weeks pass without replies.

As for the end goal, it seems fine in theory. However, I don't quite see what's better about this jwt fork than the previous jwt fork and I don't have the ability to investigate it deeply. If this is the consensus in kubernetes that's good enough for me. I am just unsure that, from the linked issue (104007) alone that this where the rest of the k8s community is going. Also, because heketi is no-one's focus I hope that this area doesn't continue to churn - as it makes things harder for us to keep up with.

All in all, thanks for the heads up - I'll take a look at the PR itself next - and we'll keep an eye on these items for heketi as well as the k8s issue.

**Comment by phlogistonjohn** [comment]
The 'go modules' work has been merged. You should now be able to rebase against the master branch and force push your pr. Thanks!

**Comment by Haimantika** [comment]
> The 'go modules' work has been merged. You should now be able to rebase against the master branch and force push your pr. Thanks!

Thanks! Will do it.

**Comment by phlogistonjohn** [comment]
This is done. Released as part of heketi v10.4.0.
