### ISSUE TITLE
Is increasing the replica of heketi deployment supported, can we run more that 1 heketi pod in production cluster

### ISSUE THREAD

**Issue by Nirm01** [heketi/heketi#1879]
root@caasng-bgl-ctrl1 ~]# kubectl get pods | grep heketi
heketi-9d77d4dc-8lmwp   0/1     Running   3          3m59s
heketi-9d77d4dc-pcpc9   1/1     Running   0          2d6h
heketi-9d77d4dc-rfvlc   0/1     Running   3          3m59s

only 1 pod is in ready state other 2 are just restarting

**Comment by phlogistonjohn** [comment]
No, it is not. Heketi's database is single-reader single-writer and so scaling up a heketi deployment is not going to work.

You can run multiple istances of heketi in different namespaces managing different gluster instances all with unique dbs FWIW.

If this answers the question, can we close this issue?

**Comment by Nirm01** [comment]
I created heketi deployment using gk_deploy script, heketi pod is created
But I see the cluster id and volumes are empty after pod restart
[root@deploy-heketi-fb9947d5b-jcbsm /]# heketi-cli  cluster list
Clusters:

[root@deploy-heketi-fb9947d5b-74pmc /]# df -h
Filesystem                     Size  Used Avail Use% Mounted on
overlay                        200G   66G  135G  33% /
tmpfs                           64M     0   64M   0% /dev
tmpfs                           32G     0   32G   0% /sys/fs/cgroup
/dev/mapper/root_vg-root        35G  2.8G   32G   9% /etc/hosts
tmpfs                           32G  8.0K   32G   1% /etc/heketi
/dev/mapper/docker--vg-docker  200G   66G  135G  33% /etc/hostname
shm                             64M     0   64M   0% /dev/shm
tmpfs                           32G   12K   32G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                           32G     0   32G   0% /proc/acpi
tmpfs                           32G     0   32G   0% /proc/scsi
tmpfs                           32G     0   32G   0% /sys/firmware

Heketi Db mount is missing, how to get it mounted in the heketi pod?

**Comment by phlogistonjohn** [comment]
Unfortunately, we do not maintain gk-deploy - it is unmaintained and archived on github. To be honest, if you are not already very familiar with heketi/gluster and using it for pre-existing clusters I don't really recommend using it for new installs. This project is maintenance only (see our readme).

That said, there's a bootstrapping step to be performed where a heketi instance is started with the db stored on temporary storage. During that step a cluster/topology is created then a volume and then we swap over to storing the db on that volume. I thought the gk-deploy script handled that step for you, but it's been a very long time since I last used it.

**Comment by phlogistonjohn** [comment]
I hope my previous comment was helpful.
