### ISSUE TITLE
RAID device support in API

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#266]
Add device API should support RAID device settings, which can later be used to correctly setup file systems on top of RAID.

**Comment by obnoxxx** [comment]
Not sure what this is about really. Is it about setting up software raid (like mdadm)? I thought this is below the resposibility layer of heketi. Heketi takes block devices and uses lvm on top of them. Since we're not going to implement this soon, and going to concentrate on glusterd2, I am closing this now. Can be re-opened if it's still desired.
