### ISSUE TITLE
Brick cleanup deletes the volume even if it fails with "Volume <volname> already exists"

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#293]
Try to create a volume with existing volume name. It fails with error "Stderr [volume create: vol23: failed: Volume vol23 already exists" and run the brick cleanup.

I think related commit https://github.com/heketi/heketi/commit/dd2a70dbfd7d3ee0a58d39799ed13bce260d4bd1

Should give a error and exit if the volume is already up and running, instead of deleting it.

**Comment by lpabon** [comment]
Nice bug! Normally we do not set the volume name since that is not normal usage, so I would have not noticed this.  I'll investigate further.

**Comment by lpabon** [comment]
The issue is that when the volume creation fails, it calls volume.Destroy() for that volume name.  What we should do is instead check the return value of https://github.com/heketi/heketi/blob/master/apps/glusterfs/volume_entry.go#L300 . If it is something like "ErrVolumeNameAlreadyExists" then it should return that error.  Then the error should be checked in https://github.com/heketi/heketi/blob/master/apps/glusterfs/volume_entry.go#L307 so that it doesn't call v.Destroy()
