### ISSUE TITLE
Test Gluster/Heketi setup in Kubernetes

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#449]
This alone is important. No need to for petsets or daemon sets here. We just need to determine if the communication works, not worrying about deployment.

**Comment by MohamedAshiqrh** [comment]
Hi,

I have been looking into the issue for some time now. Issue noticed is the way heketi validates the pod is not successful in case of kubernetes(unlike openshift). Issue can be fixed by Authenticating pods in kubernetes without username and password. Adding another way to Authenticate, which is by BearerToken. BearerToken can be created using a service account. The fix also solves this [issue](https://github.com/heketi/heketi/issues/508).

**Comment by lpabon** [comment]
Closed by #544
