### ISSUE TITLE
Deploy Gluster containers using PetSet or DaemonSet

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#450]
We need to determine how to deploy Gluster containers using PetSet or DaemonSet in Kubernetes.  This model will require a new way for Heketi to find the Gluster containers running on the cluster.  To execute commands, Kubernetes requires the name of the _pod_ for communication.  Therefore, Heketi must somehow associate a node with a pod.

Currently it uses labels to associate node with pod as shown:
https://github.com/heketi/heketi/blob/master/executors/kubeexec/kubeexec.go#L249

**Comment by lpabon** [comment]
We need to determine if we can use [DeamonSets](http://kubernetes.io/docs/admin/daemons/) or [PetSets](http://kubernetes.io/docs/user-guide/petset/)

**Comment by lpabon** [comment]
Also, may want to checkout https://github.com/alezzandro/openshift-gluster-server

**Comment by humblec** [comment]
DeamonSet and Petset :  http://website-humblec.rhcloud.com/deploy-glusterfs-pods-using-openshift-templates-daemonset-part-3/
https://www.youtube.com/watch?v=bVgeXWLB4i0

**Comment by MohamedAshiqrh** [comment]
@lpabon @humblec we can use both Daemon set and Pet set. Just like we have a selection condition [now](https://github.com/heketi/heketi/blob/master/executors/kubeexec/kubeexec.go#L220). We need to add a Env variable which specifies what method is being used to deploy the pods and what is the value of the label(region="gluster"). we use host networking in container hostnames will be the same of the host machine where the container is running. As a part of topology load, we will get the hostname and IP of the container. We can just verify the labels before connecting to the glusterfs pods for further operations. Daemon set will be using [node affinity](http://kubernetes.io/docs/user-guide/node-selection/#alpha-feature-in-kubernetes-v12-node-affinity) in future. I am looking into it just to check that our solution still hold true.

**Comment by MohamedAshiqrh** [comment]
If This looks valid give a :+1: , will start working on the code changes.

**Comment by lpabon** [comment]
@MohamedAshiqrh Thanks for the info.  Let's discuss tomorrow

**Comment by lpabon** [comment]
@MohamedAshiqrh I think we need to split this work into the following:

* Test Gluster/Heketi setup in Kubernetes:  This alone is important.  No need to for petsets or daemon sets here.  We just need to determine if the communication works, not worrying about deployment.
* Deployment of Gluster/Heketi in Kubernetes:  This would focus on the deployment using PetSet/DaemonSet in that model

**Comment by lpabon** [comment]
We also need a Wiki page document describing how to use Kubernetes today (without the deployment Petset/DaemonSets).

**Comment by lpabon** [comment]
I'm going to change #449 to be the first part of the comment above.

**Comment by lpabon** [comment]
@MohamedAshiqrh I would like to move this work to Release 4, and instead focus on #449 for Release 3.  What do you think?

**Comment by MohamedAshiqrh** [comment]
@lpabon sure.

**Comment by humblec** [comment]
@MohamedAshiqrh true.. It can be used, it may need some code changes in Heketi. and it is really good to use this, but a thorough testing is required.

**Comment by lpabon** [comment]
This will be moved to Release 4.  #527 will add support for Kubernetes in Release 3.

**Comment by obnoxxx** [comment]
adding @raghavendra-talur  as discussed today

**Comment by munnerz** [comment]
Hi all

I've been working on running GlusterFS server within a k8s cluster using a PetSet - I've got a demo up here: https://github.com/munnerz/k8s-gluster-petset, and am working on getting Heketi working with it too. I'm not using the hostNetwork to create the cluster, and I'm using the PetSet-generated Endpoints to actually connect to the cluster.

Interested to hear any of your thoughts on this, and hopefully there's some useful info in there for you to use. I've rebuilt the docker images used here too, as the ones on Dockerhub *required* a privileged container due to the unnecessary use of systemd.

**Comment by lpabon** [comment]
@raghavendra-talur @MohamedAshiqrh Any status on this?

**Comment by lpabon** [comment]
@MohamedAshiqrh @raghavendra-talur I changed the title and the summary of the request to be more focused on petset/daemonset.

**Comment by raghavendra-talur** [comment]
As already mentioned in comment 1, we have to evaluate/change how Heketi would discover Gluster pods depending on the deployment strategy used. I have looked at examples provided by @munnerz and also by @alezzandro and they prove the DaemonSets and PetSets both would work with minimal/no changes in Heketi's code.

1. IMO, more important aspect to consider is upgrade model. PetSet's mechanism to update pods is very similar to that of rolling upgrade of Gluster.

2. From an admin's standpoint, naming of pods in ordinal way as in PetSets might be very useful.

What is unknown is summarized well in last section of PetSet documentation, which is

There are a LOT of planned improvements since PetSet is still in alpha.
1. Data gravity and local storage
2. Richer notification events
3. Public network identities
4. WAN cluster deployments (multi-AZ/region/cloud provider)
5. Image and node upgrades

I am not sure about any change that the above features might bring in, which might result in conflict with Gluster's operation. This is considering the fact that PetSets are being designed with those applications in mind that need stable membership behavior and not just daemon behavior.

A one line summary as of today is: DaemonSets are sufficient for Gluster's use case. PetSets offers more convenience with the risk of a conflict in use case in future.

**Comment by jarrpa** [comment]
To revive this: offhand, I'm leaning towards DaemonSets. I don't see it as inherently useful to keep GlusterFS pods as pets. I see no reason why podA should prefer node1 over node2 other than admins not being comfortable with how containers work. While PetSets/StatefulSets do provide utility in their ability to selectively update nodes (e.g. add a new container spec then don't apply it to a given pod until you trigger a recreate by deleting it), the DaemonSet documentation (as best we can trust it) states:

> Support for updating DaemonSets and controlled updating of nodes is planned.

Which would likely allow for a rolling update functionality. Thus, it would seem more sensible to go with DaemonSets and expect new features than to go with PetSets and have to look out for regressions.

**Comment by jarrpa** [comment]
Resolved by #596, I believe?

**Comment by lpabon** [comment]
Yes, @jarrpa . Closed by #596
