### ISSUE TITLE
Heketi using filesystem directories

### ISSUE THREAD

**Issue by igor-petruk** [heketi/heketi#645]
I wonder if it is possible to add support of plain directories, instead of block devices in the topology. GlusterFS seems to be capable of creating volumes on the top of plain filesystem directories

**Comment by lpabon** [comment]
Hi @igor-petruk , 
  This is not possible because Heketi is used to provision storage from many sources across the cluster (creating LVs where it needs to).  Working on file system would require the bricks to be created already and that is what Heketi is doing (it would be like a catch-22).  Or, if no bricks where to be created, then this would heavily depend on quotas from the file system which we currently do not need due to using LVs.  We have no plans for this in the foreseeable future.
