### ISSUE TITLE
Validate topology.json

### ISSUE THREAD

**Issue by sterburg** [heketi/heketi#669]
I've made the mistake of entering a _hostname_ where i should have entered an _ip-address_ in the topology.json at clusters[{nodes[{node.hostnames.storage[0]}]}].

This was perfectly accepted by both gk-deploy and heketi-cli.
Running the command `heketi-cli setup-openshift-heketi-storage` then generates an invalid heketi-storage.json because the generated endpoint object contains hostnames instead of ip-addresses, which endpoint api does not accept.
gk-deploy then runs `oc create -f heketi-storage.json` and failes at creating the endpoints object, but creates all the other objects, including the heketi-storage-copy-job.
The heketi-storage-copy-job then fails to start the pod because it cannot mount the gluster volume because the endpoint is not there.

Because the gk-deploy tool will do an `abort` at the end (`gk-deploy: check_pods "job-name=heketi-storage-copy-job" "Completed"`)  , this heketi-storage-copy-job pod gets deleted along with all the logging it had, so it was hard to find the root cause. Hint: debug output all logs & events related to pod before doing an `abort`.

Fixing the topology.json and re-running gk-deploy is not so easy at this stage.
Because gk-deploy did an abort and deleted all the objects, but leaves the LVM intact a re-run of gk-deploy fails on `pvcreate: Can't initialize physical volume "/dev/sda" without -ff`.

**Comment by lpabon** [comment]
Good points @sterburg . Looks like a couple of issues:

1. Does glusterfs in kubernetes support hostnames?  If not, then the code should verify that it is an IP.  (but I think it probably does)
1. Looks like `gk-deploy` may need some checking before continuing to the next step.
1. `pvcreate -ff` Is something that may need to be discussed.  The issue here is that we do not want Heketi to destroy a disk if it contained _something_ which caused pvcreate not to succeed.  I can probably guess that what happened is that the disks were initialized but the db was not backed up since the volume was not created.  If Heketi restarted, then the db was deleted and it did not know it had already initialized them.  This is fixed in #671 by backing up the database to a secret iff in a Kubernetes cluster.

**Comment by lpabon** [comment]
CC @jarrpa

**Comment by sterburg** [comment]
This is the resulting endpoint:
# oc export ep heketi-storage-endpoints
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  name: heketi-storage-endpoints
subsets:
- addresses:
  - ip: 192.168.0.20
  - ip: 192.168.0.51
  - ip: 192.168.0.54
  ports:
  - port: 1
    protocol: TCP

This is the API doc:
https://docs.openshift.com/container-platform/3.4/rest_api/kubernetes_v1.html#v1-endpoints
https://docs.openshift.com/container-platform/3.4/rest_api/kubernetes_v1.html#v1-endpointaddress
It states that the "ip" attribute need to be an IP address. A hostname is not possible.

Gluster will support hostnames, but the "endpoints" API object of kubernetes does not.

**Comment by phlogistonjohn** [comment]
Last activity on this issue was over a year ago. Closing. Please reopen if additional discussion is needed.
