### ISSUE TITLE
Make heketi highly-available

### ISSUE THREAD

**Issue by harryge00** [heketi/heketi#703]
I just wonder, if it is possible to make heketi highly-available? I think this may be a huge feature because it is not easy to make multiple heketi instances writing to the same boltdb at the same time safely.

**Comment by lpabon** [comment]
Correct.  In a way, this can be achieved by running on a kubernetes cluster.  Kubernetes keeps track of the container running and also provides the [service](https://kubernetes.io/docs/user-guide/services/) which allows access to the container running anywhere in the cluster.

**Comment by obnoxxx** [comment]
@harryge00 Note that high availability does mean to have multiple heketi instances running at the same time, writing to the same DB. High availability means to make sure that a (one) heketi instance is always reachable, i.e. more a failover-solution which, as @lpabon explained can for instance be achieved by running in a kubernetes cluster. The multiple-writers/instances part is a scale-out / loadbalancing / all-active aspect. I am not sure why one would want this. In order to require this, you'd have to have an *awful* lot of requests (to create / delete / ... volumes) coming in simultaneously, e.g. tens or hundreds per second, is my idea. Maybe you have such an environment. Maybe I am wrong in this assumption about usefulness of scaling out the heketi API head. What am I missing?

**Comment by harryge00** [comment]
@obnoxxx  Thanks very much for your detailed reply. I have previously pinned the heketi on a kubernetes node, with hostpath as the volume. And when the kube-node went down, the instance stopped providing service. I have now unpinned it, and even when the node goes down, it can be deployed to another node.
