### ISSUE TITLE
When ls cannot find a directory it is shown as an error in logs 

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#715]
PR #686 introduced a change which is being logged as an error.  This needs to be fixed so that it does not log an error.

Example:

```
[sshexec] ERROR 2017/03/14 11:16:54 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Failed to run command [sudo /bin/bash -c 'ls /var/lib/heketi/mounts/vg_9531f36340f2443cf1fa523884ae3209'] on 192.168.10.102:22: Err[Process exited with: 2. Reason was:  ()]: Stdout []: Stderr [ls: cannot access /var/lib/heketi/mounts/vg_9531f36340f2443cf1fa523884ae3209: No such file or directory
]
[heketi] INFO 2017/03/14 11:16:54 Deleted node [9531f36340f2443cf1fa523884ae3209]
[asynchttp] INFO 2017/03/14 11:16:54 Completed job 67358b97b782fd70b3a4b7e59d41482b in 4.563562664s
[sshexec] ERROR 2017/03/14 11:16:54 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Failed to run command [sudo /bin/bash -c 'ls /var/lib/heketi/mounts/vg_8f3ae5eb4c5bc065fc9752686ae75568'] on 192.168.10.102:22: Err[Process exited with: 2. Reason was:  ()]: Stdout []: Stderr [ls: cannot access /var/lib/heketi/mounts/vg_8f3ae5eb4c5bc065fc9752686ae75568: No such file or directory
]
```

**Comment by obnoxxx** [comment]
Ah, I was wondering what these errors are all about... ;-)

**Comment by obnoxxx** [comment]
Ok, I looked at the code. The error logging is coming from the actual ssh utility code. That means the caller currently does not have a choice to log or not log an error. In our case, the intention of the ssh executor is to check a condition. The error is one of the possible valid outcomes.

Hence in order to facilitate this use case, we could either make the logging in SshExec.ConnectAndExec() all info only or stop logging in ConnectAndExec() altogether and instead just return the error and leave it up to the caller to log.

I think I'd go the latter way.

**Comment by phlogistonjohn** [comment]
IIRC this call to the `ls` command has been removed.
Stale issue. Closing.
