### ISSUE TITLE
Lack of distributed volume support

### ISSUE THREAD

**Issue by atinmu** [heketi/heketi#72]
I see in create volume API, replica string is optional and the default nature is to create a 2 way replica volume which limits an user to have a plain distributed volume.

**Comment by lpabon** [comment]
Hi Atin, the goal of Heketi is for users not to worry about volume characteristics. Replica is used because it is not something which can be figured out automatically.  Distribution of bricks is automatically determined and therefore is no need to ask the user.  Please take a look at the prototype to see how Heketi was able to determine the number of bricks to distribute:

https://github.com/heketi/heketi/blob/prototype/plugins/glusterfs/handler_volume.go#L147

- Luis
