### ISSUE TITLE
Disk space is not fully used

### ISSUE THREAD

**Issue by zhaorendong** [heketi/heketi#747]
I had created topology with 1 cluster,3 nodes and 6 devices per node.When I create PVC with 2.4Ti and create Storageclass with volumeType "Replica: 3",The Heketi will create 12 bricks, but every bricks is not fully used space of device.For example: the size of device is 837,then the brick used 614Gi and free 220Gi, but the 220Gi can not be used.Following:
Devices:
                Id:111b937d52f80de8f92b330af562d918   Name:/dev/sdd            State:online    Size (GiB):837     Used (GiB):617     Free (GiB):220     
                        Bricks:
                                Id:85e4528c60a1284af0bd7ce7727a65a3   Size (GiB):614     Path: /var/lib/heketi/mounts/vg_111b937d52f80de8f92b330af562d918/brick_85e4528c60a1284af0bd7ce7727a65a3/brick
                Id:536c8d8daf7136536533827872155919   Name:/dev/sdb            State:online    Size (GiB):837     Used (GiB):617     Free (GiB):220     
                        Bricks:
                                Id:71d5c9f8829f8a15c7ee4ef89c26c1c6   Size (GiB):614     Path: /var/lib/heketi/mounts/vg_536c8d8daf7136536533827872155919/brick_71d5c9f8829f8a15c7ee4ef89c26c1c6/brick
                Id:652fb67d15ff0f09f97ad19fe957ed93   Name:/dev/sdf            State:online    Size (GiB):837     Used (GiB):617     Free (GiB):220     
                        Bricks:
                                Id:eba69219112446db9dedcb1c3849c708   Size (GiB):614     Path: /var/lib/heketi/mounts/vg_652fb67d15ff0f09f97ad19fe957ed93/brick_eba69219112446db9dedcb1c3849c708/brick
                Id:78434a0cf6e0a8c39b987bf0277289a5   Name:/dev/sde            State:online    Size (GiB):837     Used (GiB):0       Free (GiB):837     
                        Bricks:
                Id:837eaf2fc4933974fb5453e5e2246ffe   Name:/dev/sdc            State:online    Size (GiB):837     Used (GiB):0       Free (GiB):837     
                        Bricks:
                Id:eb71fb2c417fae6658d6e36abbaecfd4   Name:/dev/sdg            State:online    Size (GiB):837     Used (GiB):617     Free (GiB):220     
                        Bricks:
                                Id:e6d5810c87bcf59437ef24df0299a63b   Size (GiB):614     Path: /var/lib/heketi/mounts/vg_eb71fb2c417fae6658d6e36abbaecfd4/brick_e6d5810c87bcf59437ef24df0299a63b/brick

**Comment by obnoxxx** [comment]
The reason for this is that heketi breaks down the size by division by two:

* It will first look for 2.4 TiB (2458GiB) disks ==> not found
* then it will look for (2.4)/2 TiB ==  1229 GiB disks ==> not found
* then it will look for (2.4)(2*2) TiB == 614.5 GiB disks ==> found

If we were doing division by n , n+1 .... instead of powers of 2, then you would have seen bricks of size 2.4 / 3 TiB == 820 GiB. I have been thinking about doing that recently, but up to now, the powers-of-two division seems to have been good enough. There are pros and cons for both approaches.

I think the above answers your "why" question.
I will close this issue. Feel free to reopen if questions remain, and feel free to file an RFE if you would like to propose this to be done differently.

**Comment by zhaorendong** [comment]
Thank you! But if the size of device is 837,then the brick used 614Gi and free 220Gi, and a total of 5 disks were used.So there are 5 bricks free 220Gi. At this time,I can not create PVC with 1100Gi.

**Comment by obnoxxx** [comment]
From the above it looks like 4 disks were used (not 5), which confirms my explanation. I.e. you have 4 bricks of 614GiB used on each node. I.e. each node now has 2 unused disks of 837 GiB (sdc and sde above) and 4 disk with 220GiB free each (sdd, sdb, sdf, sdg).

So a create of 1100GiB should succeed with 2 replica sets of 550 GiB each (consuming sdc and sde above).
Did you try this? If yes, and it failed, can you provide more details on the failure?

It can not be guaranteed though that the available space can always be fully consumed, because we do not only need to consider the net disk space available but also how the bricks of a volume need to be spread across failure domains (nodes) along with the restriction that all bricks of a volume are currently of the same size.

**Comment by zhaorendong** [comment]
Yes，I have 4 bricks of 614GiB used on each node and each node now has 2 unused disks of 837 GiB (sdc and sde above) and 4 disk with 220GiB free each (sdd, sdb, sdf, sdg), so there are (827*2+220*4=2554)GiB that I can use, right? But I can not create PVC with 2554GiB .

**Comment by obnoxxx** [comment]
This is due to the fact that we always need to over-allocate the bricks a little more than the pure space requested: There is some additional space needed for metadata, and (if enabled) a certain percentage for snapshots. So you will always need at least some 0.5% more space than your calculation yields.

So e.g. requesting 2500 GiB instead 2554 should theoretically work (unless you request snapshot  space),
but you might need to split the size up too much, and reach too many bricks. (ErrNoSpace because of too many bricks in the requested volume.) This can be avoided by configuring a different MaxBricks setting: This is defaulting to 32, but can be changed in the config file with the setting of max_bricks_per_volume.

It could be that with the +1 allocator iteration you would end up better than with the current *2 allocator iteration, but that would be worse for other constellations I believe. Worth trying out though...

**Comment by zhaorendong** [comment]
OK! Thank you!
