### ISSUE TITLE
Is heketi secured from reusing JWT (Do we need TLS)?

### ISSUE THREAD

**Issue by shiroari** [heketi/heketi#758]
Hi,

As I can see heketi requires a few JWT claims and it seems to me that requests are not protected from being replayed until JWT is expired. Do you consider to implement TLS support for the server to protect JWT tokens? I guess some requests, for instance, creating a volume could be used to exhaust cluster resources. How critical do you think replaying could be?

**Comment by lpabon** [comment]
@shiroari Hi. I thought a lot about this when I first created it. I tried to keep it as simple as possible so I didn't use HTTPS (which is a pain to setup.. .certs etc). Since this is just a provisioner, and "supposed" to be in the same datacenter as the client (be it Kubernetes or something else), then I thought that the risk would be quite minor based on JWT. I hope this answers your question. I will close the issue, but please feel free to open it again if you have more questions.

**Comment by shiroari** [comment]
@lpabon thank you
