### ISSUE TITLE
support for configuring glusterfs with ext4

### ISSUE THREAD

**Issue by adityakali** [heketi/heketi#764]
I was trying to bring up the heketi cluster on Kubernetes as described at https://github.com/gluster/gluster-kubernetes on GCE with a custom [Container-Optimized OS](https://cloud.google.com/container-optimized-os/) image. After working around a [known issue](https://github.com/gluster/gluster-kubernetes/issues/19) I managed to make progress until heketi tries to format & mount the volumes in glusterfs pods:

```
[kubeexec] DEBUG 2017/05/17 21:39:53 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kubernetes-minion-group-1qfb Pod: glusterfs-j036k Command: mkdir -p /var/lib/heketi/mounts/vg_7b6dce0beb3907cad7a417abb3b6c594/brick_0ff04f0d4fb334c9803f7cb4dd2394cc
Result: 
[kubeexec] DEBUG 2017/05/17 21:39:54 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kubernetes-minion-group-1qfb Pod: glusterfs-j036k Command: lvcreate --poolmetadatasize 12288K -c 256K -L 2097152K -T vg_7b6dce0beb3907cad7a417abb3b6c594/tp_0ff04f0d4fb334c9803f7cb4dd2394cc -V 2097152K -n brick_0ff04f0d4fb334c9803f7cb4dd2394cc
Result:   Using default stripesize 64.00 KiB.
  Logical volume "brick_0ff04f0d4fb334c9803f7cb4dd2394cc" created.
[kubeexec] DEBUG 2017/05/17 21:39:55 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kubernetes-minion-group-1qfb Pod: glusterfs-j036k Command: mkfs.xfs -i size=512 -n size=8192 /dev/mapper/vg_7b6dce0beb3907cad7a417abb3b6c594-brick_0ff04f0d4fb334c9803f7cb4dd2394cc
Result: meta-data=/dev/mapper/vg_7b6dce0beb3907cad7a417abb3b6c594-brick_0ff04f0d4fb334c9803f7cb4dd2394cc isize=512    agcount=8, agsize=65472 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=0, sparse=0
data     =                       bsize=4096   blocks=523776, imaxpct=25
         =                       sunit=64     swidth=64 blks
naming   =version 2              bsize=8192   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
[kubeexec] DEBUG 2017/05/17 21:39:55 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:250: Host: kubernetes-minion-group-1qfb Pod: glusterfs-j036k Command: echo "/dev/mapper/vg_7b6dce0beb3907cad7a417abb3b6c594-brick_0ff04f0d4fb334c9803f7cb4dd2394cc /var/lib/heketi/mounts/vg_7b6dce0beb3907cad7a417abb3b6c594/brick_0ff04f0d4fb334c9803f7cb4dd2394cc xfs rw,inode64,noatime,nouuid 1 2" | tee -a /var/lib/heketi/fstab > /dev/null
Result: 
[kubeexec] ERROR 2017/05/17 21:39:55 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:247: Failed to run command [mount -o rw,inode64,noatime,nouuid /dev/mapper/vg_7b6dce0beb3907cad7a417abb3b6c594-brick_0ff04f0d4fb334c9803f7cb4dd2394cc /var/lib/heketi/mounts/vg_7b6dce0beb3907cad7a417abb3b6c594/brick_0ff04f0d4fb334c9803f7cb4dd2394cc] on glusterfs-j036k: Err[command terminated with exit code 32]: Stdout []: Stderr [mount: unknown filesystem type 'xfs'
]
```

After a bit of debugging, it seems that heketi only tries to format and mount the glusterfs volumes as xfs ([related code](https://github.com/heketi/heketi/blob/master/executors/sshexec/brick.go#L78)) and the OS kernel does not have XFS filesytem support. 

Is it possible for heketi-cli to (as an option) support creating ext4 formatted glusterfs volumes? It will need an update to the `heketi/gluster` docker image as well.

I am totally noob at this and I don't know if there are any xfs dependencies in heketi or glusterfs that makes working with ext4 impossible. Please correct me if this is an unreasonable request.

Thanks!

**Comment by lpabon** [comment]
@obnoxxx Does glusterfs support ext4?

cc @heketi/dev

**Comment by fcami** [comment]
Quoting http://lists.gluster.org/pipermail/gluster-users/2014-March/016534.html "If at all possible, use xfs instead of ext4. This is an official recommendation.".
See also http://lists.gluster.org/pipermail/gluster-users.old/2014-November/019436.html

The upstream QSG uses XFS: http://gluster.readthedocs.io/en/latest/Quick-Start-Guide/Quickstart/ - the official documentation recommends XFS as well: https://gluster.readthedocs.io/en/latest/Install-Guide/Common_criteria/

So while ext4 is known to work XFS seems recommended by Gluster.

**Comment by adityakali** [comment]
If ext4 can be supported as an option (not necessarily default), it will be great as well.

**Comment by lpabon** [comment]
Hmm, we can take a look, but I am concerned that there is no documentation on what the correct settings are for ext4. Which would mean that since Heketi created those FSs, it would be responsible.  Can someone provide the correct settings for the file system? See the [XFS ones](https://github.com/heketi/heketi/blob/master/executors/sshexec/brick.go#L78).

**Comment by fcami** [comment]
There is no recommended setting in the current documentation. I went back to 2012 using the Internet Archive to browse older docs that are not available online anymore and even these were XFS-only. I don't think it'd be a good idea to even provide an option in heketi to use ext4 provided Gluster upstream does not recommend it and obviously doesn't test anymore.

@adityakali is there any reason you can't compile the XFS module for your kernel?

**Comment by apcheamitru** [comment]
I'm interested in ext4 support for Heketi too.  I'm running GlusterFS on an ODROID-C1+ cluster ([3.10 kernel](https://github.com/hardkernel/linux/tree/odroidc-3.10.y)).  XFS did not support user namespaces until kernel 3.12, so it is disabled in Hardkernel's configuration.

I am currently in the process of compiling a kernel that supports XFS.  I'd prefer to use XFS, but since Gluster supports ext4 I think it is reasonable for Heketi to support ext4 as well.

Thanks!

**Comment by phlogistonjohn** [comment]
While I appreciate the annoyance/challenge of having to recompile your kernel just to use Heketi & Gluster it seems that allowing ext4 is risky as it's support status is questionable. I also shudder at the arm ecosystem's habit of using old kernels so frequently.

Given that, I'd personally decline adding ext4 support to Heketi. But I'll leave this issue open a little while longer for any additional discussion. If anyone else on the Heketi team disagrees with me please say so.

**Comment by apcheamitru** [comment]
Thanks John.  I'm all set with XFS and an updated kernel, so this isn't blocking me anymore.  And yes, I would like to see newer kernels available for these SoCs, but I understand why that's a challenge.

But I don't think I would say that ext4's support status is "questionable"...

The [Gluster Install Guide](https://docs.gluster.org/en/v3/Install-Guide/Common_criteria/) states: _"Typically, XFS is recommended but it can be used with other filesystems as well. Most commonly EXT4 is used when XFS isn’t, but you can (and many, many people do) use another filesystem that suits you."_

Additionally, Red Hat has fixed ext4-related bugs in the past.  For example, [Bug 1100204 - brick failure detection does not work for ext4 filesystems](https://bugzilla.redhat.com/show_bug.cgi?id=1100204).  That effort does indicate some level of support.

My interpretation of the current state of Gluster + ext4 is that this configuration is __supported, but not recommended__.

I generally feel that interfaces like this should strive to support all valid configurations of the underlying technology, when reasonable.  Ext4 is a valid configuration.  I don't know if there's a large enough user base to consider this a "reasonable" feature request.  Red Hat suggests that "many, many people" use a filesystem other than XFS... let's see if anyone else chimes in to this discussion.

With that being said, I don't have a horse in this race anymore.  I was attempting to use Ext4 for a proof-of-concept because of a hardware/kernel limitation unique to my platform.  I was able to workaround my particular issue.

It does seem like a relatively simple change in [brick.go](https://github.com/heketi/heketi/blob/master/executors/cmdexec/brick.go) though...

**Comment by adityakali** [comment]
Sorry for not following up on this earlier.
GlusterFS + Ext4 is used on Kubernetes often. And we haven't seen issues because of Ext4 on it. Ext4 is the default linux FS on many distros, so I wouldn't count it as having questionable support :)

I think having ext4 as an option is the best way to allow users to actually try it, write tests, and gather feedback too.

**Comment by nixpanic** [comment]
I can remember one of the problems that come up sometimes with ext4, but not on XFS. When a busy system has an unexpected reboot (power failure), the filesystems need to be checked. For ext4 this is done with `fsck` and (often?) involves a manual action from an admin. XFS has the filesystemcheck in the kernel module, and handles (more?) automatically. Being able to mount the bricks after a fatal issue is obviously important, even more so with container environments where storage is expected to be a self-serve-service.

IMHO we should opt for the best experience that we can offer our users. At the moment for me, that is bricks formatted as XFS. (Also note that all Gluster testing by developers and Red Hat is done on XFS.)

If there are good arguments to support ext4 in Heketi, we would surely accept good quality patches that make it an option.

**Comment by apcheamitru** [comment]
> I can remember one of the problems that come up sometimes with ext4, but not on XFS. When a busy system has an unexpected reboot (power failure), the filesystems need to be checked. For ext4 this is done with `fsck` and (often?) involves a manual action from an admin. XFS has the filesystemcheck in the kernel module, and handles (more?) automatically.

XFS will replay the journal on mount to fix any inconsistencies caused by an unclean shutdown.  Ext4 is also a journaled filesystem and will do this too. 

The difference is that when <code>fsck.ext4</code> is called on boot, it will actually perform a filesystem check.  On the other hand, <code>fsck.xfs</code> is just a shell script that instructs the user to run <code>xfs_repair</code> and then exits immediately with an exit code of 0... this is why Ext4 could require more attention from an admin. 

For less manual intervention, fstab could be configured so that filesystem consistency isn't checked on boot.  It would also make sense to adjust the "maximum mount count" and "check interval" filesystem parameters with <code>tune2fs</code>.

True filesystem corruption - for example, as result of a failing disk - will require some level of interaction regardless of which filesystem is being used; neither XFS or Ext4 is automatic.

> IMHO we should opt for the best experience that we can offer our users. At the moment for me, that is bricks formatted as XFS. (Also note that all Gluster testing by developers and Red Hat is done on XFS.)

Good point.  Red Hat certainly seems to prefer XFS and I imagine that's the most commonly implemented configuration.  Apart from a couple unusual use cases above, I don't know if there's a good reason to choose Ext4 over XFS.

If Heketi does decide to support Ext4, XFS should probably be the default behavior.  And a "use at your own risk" or "not recommended for production use" disclaimer might be in order for Ext4.

**Comment by phlogistonjohn** [comment]
Stale issue. Closing.
