### ISSUE TITLE
Add version to heketi/heketi:dev dockerimage

### ISSUE THREAD

**Issue by andersla** [heketi/heketi#768]
Currently the latest-stable heketi/heketi docker image is outdated.
The heketi/heketi:dev image gets built much more often, and could be much more useful if there were some kind of versioning included in the tag (build date?). Currently if the dev image breaks there is no way to revert to a previous working dev image and the heketi deployment stays broken.
Or is there a way to pull a previous build that I don't know of?

**Comment by MohamedAshiqrh** [comment]
We will be releasing a new version soon which will include all the new features. For now yeah there is no other image except for dev which is updated and there is no way to revert back to the previous image. If you really want to revert back you can store the previous images with different tag in your local repository and then update so that you can have a backup.

**Comment by lpabon** [comment]
The dev image is supposed to be bleeding edge so it may or may not work.  We will be releasing heketi/heketi:5 and updating heketi/heketi images as soon as Release 5 is done.
