### ISSUE TITLE
Feature needed: expand a volume using lvm resize 

### ISSUE THREAD

**Issue by jsvisa** [heketi/heketi#783]
Hi, does it support the way LVM resizing, to expand a volume. If it doesn't, why not?

**Comment by lpabon** [comment]
@jsvisa  It expands the volume by adding bricks. I'm not 100% percent sure if increasing a brick size while the volume is running (lvm resize then xfs grow) would be reliable. Does that answer your question?

**Comment by jsvisa** [comment]
@lpabon Thanks for your reply. [As the document said](https://wiki.archlinux.org/index.php/LVM#Growing)

> While enlarging a file system can often be done on-line (i.e. while it is mounted)

In my test case, the LVM enlarging on XFS always succeed.

**Comment by lpabon** [comment]
@jsvisa Oh yeah, I agree, but that is not what I meant. I mean, can GlusterFS allow a brick to grow. @heketi/dev Do you guys know?

**Comment by tanner-bruce** [comment]
@lpabon it looks like gdeploy does it: https://github.com/gluster-deploy/gdeploy/blob/master/docs/source/features/lvm.rst

**Comment by lpabon** [comment]
@jsvisa Why would you want to do this? Sorry, but I don't understand the use case. Could you provide one?

**Comment by jsvisa** [comment]
@lpabon Thanks for your replay. 

Firstly, one brick stands for one system process, if a gluster node has multiple processes, leads to some performance issues;
Secondly, when another brick added into one volume, data migrating happened, this also lead to some performance issue.

**Comment by tanner-bruce** [comment]
@lpabon we also have a separate use case:

We have cluster A and cluster B. A has a volume that geo-replicates to a volume on B. Every week, we take a snapshot of B. We then clone that snapshot into multiple volumes (after deleting the old ones) to provide multiple working environments which take advantage of thin pools so we don't need to make multiple copies of the 10TB volume.

Our issue arose when we wanted to expand the volumes. We expanded the master and it worked well, then we expanded the slave volume on B. The volume is successfully expanded, however, because the thin pools work on a volume group, and heketi adds a new volume group instead of expanding the existing one, this has lead to the thin pool thin's overflowing the available capacity of the volume group, which led to a hard crash of gluster and required us to restore from backups.

This whole process is definitely outside the use case of heketi (although in my opinion it works quite nicely, and I could see others using it as well), however, having the option to expand the VG instead of adding a new VG would fully enable us to continue on this way.

**Comment by phlogistonjohn** [comment]
There's a use case here for volumes that contain very large files esp. because gluster sharding is not considered a general use xlator.
However this issue is very stale and is unlikely to be worked on.

**Comment by yjbdsky** [comment]
expand volume 1G to 2G,, but i can not write 2G file
`dd if=/dev/zero of=/mount/path/glusterfs/volume bs=1M count=2048
`
ERROR: No space left on device

**Comment by jsvisa** [comment]
> expand volume 1G to 2G,, but i can not write 2G file
> `dd if=/dev/zero of=/mount/path/glusterfs/volume bs=1M count=2048 `
> ERROR: No space left on device

Check the of `/mount/path/glusterfs/volumee` before use, (such as `df -h` to see the actual size).
