### ISSUE TITLE
use proper golang tests tools

### ISSUE THREAD

**Issue by purpleidea** [heketi/heketi#851]
Seeing what failed in a golang test is easy using the standard tests...
Why do we have heketi/tests ???

**Comment by purpleidea** [comment]
Using obscure semantics makes it hard for new users to contribute, and raises the barrier, thus making possible contributors ignore you... I'm an experienced golang developer, and this is annoying me.

Sorry for the rant!

**Comment by obnoxxx** [comment]
Right, @purpleidea , this is not very helpful, since not constructive.

What do you mean, "why do we have heketi/tests"? The directory that contains the functional tests?

What, according to you, are "standard tests"?
Example of how to use them? What explicitly changes?

if you directly run `go test -v github.com/heketi/heketi/apps/glusterfs/` you see better
what test fails. Since it's not the test that segfaults but the server that this server log
does not list the test.

...

:-)

**Comment by purpleidea** [comment]
@obnoxxx Sorry, I was in a bad mood. Digging into new project stuff.

I'll elaborate:

Someone has built a custom "heketi test framework" : https://github.com/heketi/tests
Why does this exist instead of simply using the standard framework without any special addons?
The standard tests are: https://golang.org/pkg/testing/ (you shouldn't need an extra package, or if you do, I'd like to know why...)

The reason I was afraid of running go test -v ... (which I'm well familiar with) is that since I found some dangerous code, I wanted to first audit that test suite before I ran it and found out that it did something dangerous on my machine. The moment you see people adding `wget | sh` without a prior warning, you immediately loose trust in a code base. At least I do. Hope this was more clear and less ranty.

**Comment by obnoxxx** [comment]
@purpleidea First of all, the wget code (which you removed) was in scripts, not in the actual golang code, but of course I understand what you mean. You could always run the tests in a development VM (it might not at all be a bad idea in general to do development in a disposable VM instead of on your production machine...). 

Secondly, I have no idea about the original need to do heketi/tests. I am more than happy to move to standards and remove custom stuff. And if you can teach us how to do that: great!

**Comment by purpleidea** [comment]
@obnoxxx I'm happy to help remove all the non-standard stuff, although I don't want to write the patch if it's going to get NACK-ed. So assuming you're okay with my plan to remove heketi/tests, then I can write it.

**Comment by obnoxxx** [comment]
@purpleidea sure, maybe you can show for a start in one place how to do it, so that we can see what whould be different. And from there we can take it to more complete replacement.

**Comment by purpleidea** [comment]
one method fixed in https://github.com/heketi/heketi/pull/863

**Comment by obnoxxx** [comment]
Let's stick with the Assert function for now. We like it. It makes the code much more easy to read. Complete reasoning inPR  #863 .
