### ISSUE TITLE
cross compilation broken

### ISSUE THREAD

**Issue by obnoxxx** [heketi/heketi#861]
Cross compilation is broken for me since #845 .

```
 $ GOOS=darwin GOARCH=amd64 go build -i -v -ldflags "-X main.HEKETI_VERSION=v5.9.9-3-ge1a71f3f-deps-tarball -extldflags '-z relro -z now'" -o heketi
runtime/internal/sys
go install runtime/internal/sys: mkdir /usr/lib/golang/pkg/darwin_amd64: permission denied
```

Or from the makefile (the same):

```
$ make darwin_amd64_dist 
GOOS=darwin GOARCH=amd64 make dist
make[1]: Entering directory '/data/obnox/devel/go/src/github.com/heketi/heketi'
go build -i -ldflags "-X main.HEKETI_VERSION=v5.0.0-71-ge1a71f3f-deps-tarball -extldflags '-z relro -z now'" -o heketi
go install runtime/internal/sys: mkdir /usr/lib/golang/pkg/darwin_amd64: permission denied
make[1]: *** [Makefile:62: heketi] Error 1
make[1]: Leaving directory '/data/obnox/devel/go/src/github.com/heketi/heketi'
make: *** [Makefile:145: darwin_amd64_dist] Error 2
```

Not sure how replacing "go install github.com/heketi/heketi" followed by "go build ..." with straight "go build -i ..." lets this happen.

**Comment by obnoxxx** [comment]
note that this is used in "make release"

**Comment by JohnStrunk** [comment]
Are you sure your go env is set up correctly?

Looks like go is trying to write the package cache into GOROOT instead of
GOPATH. That mkdir should have been /data/obnox/devel/go/pkg/darwin_amd64,
I believe.

But then it doesn't work for me either... (different error):
GOOS=darwin GOARCH=amd64 make dist
make[1]: Entering directory '/home/jstrunk/go/src/github.com/heketi/heketi'
go build -i -ldflags "-X main.HEKETI_VERSION=v5.0.0-71-ge1a71f3 -extldflags
'-z relro -z now'" -o heketi
go build: when using gccgo toolchain, please pass linker flags using
-gccgoflags, not -ldflags
# github.com/heketi/heketi/vendor/github.com/docker/docker/pkg/term
vendor/github.com/docker/docker/pkg/term/termios_darwin.go:9:23: error:
reference to undefined identifier ‘syscall.TIOCGETA’
  getTermios = syscall.TIOCGETA
                       ^
vendor/github.com/docker/docker/pkg/term/termios_darwin.go:10:23: error:
reference to undefined identifier ‘syscall.TIOCSETA’
  setTermios = syscall.TIOCSETA
                       ^
make[1]: *** [Makefile:62: heketi] Error 2
make[1]: Leaving directory '/home/jstrunk/go/src/github.com/heketi/heketi'

**Comment by obnoxxx** [comment]
hmmm strange.
I am using golang from the fedora26 RPMs.

**Comment by JohnStrunk** [comment]
Me too, and I had to manually set GOROOT, strangely enough.
By default, `go env` had `GOROOT=/usr`, and it mostly worked. The problem I had was actually w/ Glide trying to vendor the standard libs. I fixed that with `GOROOT=/usr/lib/golang`.

**Comment by obnoxxx** [comment]
oh, interesting. my `GOROOT=/usr/lib/golang` without me setting it...

**Comment by obnoxxx** [comment]
I now understood, that `go install` will try the same (and fail) if doing it for cross compilation:

```
$ GOOS=darwin GOARCH=amd64 go install github.com/heketi/heketi
go install runtime/internal/sys: mkdir /usr/lib/golang/pkg/darwin_amd64: permission denied
```

So it is actually not the bad of `go build -i` itself but more about the scope under which it's run...

**Comment by obnoxxx** [comment]
A-ha!

Found this: https://dave.cheney.net/tag/cross-compilation

It explains that cross-compilation always rebuilds the standard library, and using go install (or go build -i) this would get cached into its location which is under GOROOT... So Dave Cheney advises to use go build (without -i, and not go install) for cross compilation (or have the whole go env self-compiled somewhere).

That starts to make a lot of sense...
