### ISSUE TITLE
The docker repo heketi/gluster is empty

### ISSUE THREAD

**Issue by andersla** [heketi/heketi#890]
My deployment fails because the docker image heketi/gluster:latest is gone from repo.
https://hub.docker.com/r/heketi/gluster/tags/

**Comment by obnoxxx** [comment]
Yeah, I just removed it because it had not been updated since a while. And the advice is to use the official upstream gluster docker images. See #808 for further comments. I wanted to remove it altogether, but maybe this is the wrong way...

@raghavendra-talur @jarrpa @humblec  -  how to do it properly? where are these images used? I can't fined it used anywhere....

**Comment by andersla** [comment]
Ok I have switched, but it might be an idea to put image back for a while - or something - it has been pulled 500K times from dockerhub.

**Comment by obnoxxx** [comment]
@andersla yeah, you are right. I'll figure it out. Thanks for you hint!

**Comment by obnoxxx** [comment]
To avoid confusion, I removed the repository altogether, as was announced in #808 already. Not sure where to properly communicate this so people know where to go, which is:

https://hub.docker.com/r/gluster/gluster-centos/
