### ISSUE TITLE
How to manage volumes, e.g. "gluster volume set" via heketi in k8s

### ISSUE THREAD

**Issue by andersla** [heketi/heketi#938]
I am running Gluster on kubernetes and managed by heketi as described in docs: https://github.com/heketi/heketi/tree/master/extras/kubernetes
If I would like to tweak volumes with option: 
`gluster volume set my-gluster-vol performance.write-behind off`
How would I do this in this heketi-kubernetes setup?

**Comment by phlogistonjohn** [comment]
First, I'd mention that deploying heketi "by hand" is not recommended and we generally point people at the gluster-kubernetes project now.

As for the volume options part, newer versions of Heketi and the kubernetes volume provionioner support volume options which are passed directly to 'gluster volume set'. I am sure these are available at least in Heketi v8.0.0 and K8s version 1.10, they probably exist in earlier versions as well.

Since this issue has been idle for some time I'm closing this issue now. If you feel the issue needs additional discussion please feel free to reopen.
