### ISSUE TITLE
Is it possible to use rdma with kubernetes-heketi

### ISSUE THREAD

**Issue by hiyijian** [heketi/heketi#954]
Hi stuff,
I am trying to use infiniband rdma to boost gluster. Is it possible? I guess StorageClass might be provide a chance to set it, but it seems to be wrong and I found nothing about this in docs

**Comment by phlogistonjohn** [comment]
Sorry, but we do not support configuring RDMA via Heketi and have no plans to do so. To the best of my knowledge RDMA's continued support in gluster itself is questionable. See https://lists.gluster.org/pipermail/gluster-devel/2018-July/054990.html

Quote:

> ‘RDMA’ transport support:
>Gluster started supporting RDMA while ib-verbs was still new, and very high-end infra around that time were using Infiniband. Engineers did work with Mellanox, and got the technology into GlusterFS for better data migration, data copy. While current day kernels support very good speed with IPoIB module itself, and there are no more bandwidth for experts in these area to maintain the feature, we recommend migrating over to TCP (IP based) network for your volume.
>
>If you are successfully using RDMA transport, do get in touch with us to prioritize the migration plan for your volume. Plan is to work on this after the release, so by version 6.0, we will have a cleaner transport code, which just needs to support one type.

Because of this & the age of this issue I'm going to close the issue. If you feel this needs additional discussion please reopen the issue.
